#!/usr/bin/env python3
"""Apply hand-curated LLM-reviewed party prompts — replaces combinator spam."""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "scripts"))

from curate_content_pools import dedupe_fibbage, dedupe_mc, dedupe_statements, dedupe_strings
from hand_curated_party_prompts import DRAW_GUESS, FIBBAGE, QUIPLASH

# Additional curated pools (inline for maintainability)
SHIRT_DESIGNS = [
    'Design a shirt: "I woke up like this (disappointed)"',
    'Design a shirt: "Professional Overthinker"',
    'Design a shirt: "Error 404: Motivation not found"',
    'Design a shirt: "Powered by spite"',
    'Design a shirt: "Talk to the hand — mine\'s busy"',
    'Design a shirt: "Zero days without sarcasm"',
    'Design a shirt: "My therapist knows about you"',
    'Design a shirt: "Chaos coordinator"',
    'Design a shirt: "Emotionally unavailable since birth"',
    'Design a shirt: "I peaked in the group chat"',
    'Design a shirt: "Sorry I\'m late, I didn\'t want to come"',
    'Design a shirt: "Certified disaster human"',
    'Design a shirt: "Low battery, please charge"',
    'Design a shirt: "Do not perceive me"',
    'Design a shirt: "Main character (unpaid)"',
    'Design a shirt: "Hot mess express"',
    'Design a shirt: "Feral but make it fashion"',
    'Design a shirt: "No thoughts, head empty"',
    'Design a shirt: "Touch grass (refused)"',
    'Design a shirt: "Gaslight, gatekeep, girlboss"',
    'Design a shirt: "Roster manager since 2019"',
    'Design a shirt: "Red flag collector"',
    'Design a shirt: "Situationship survivor"',
    'Design a shirt: "Walk of shame speedrun any%"',
    'Design a shirt: "2am decisions club"',
    'Design a shirt: "Hangxiety loading..."',
    'Design a shirt: "Delulu is the solulu"',
    'Design a shirt: "Soft launch hard landing"',
    'Design a shirt: "Read receipts ruin lives"',
    'Design a shirt: "Ghosted and gorgeous"',
    'Design a shirt: "Brunch is my religion"',
    'Design a shirt: "Powered by gas station sushi"',
    'Design a shirt: "My Roman Empire is real"',
    'Design a shirt: "Group chat witness protection"',
    'Design a shirt: "Finsta admin"',
    'Design a shirt: "Uber pool trauma"',
    'Design a shirt: "Vegas mistakes alumni"',
    'Design a shirt: "Spring break was a mistake"',
    'Design a shirt: "Frat formal fashion victim"',
    'Design a shirt: "Pregame stretches only"',
    'Design a shirt: "Leg day never"',
    'Design a shirt: "Gains? Debatable"',
    'Design a shirt: "Student loan speedrun"',
    'Design a shirt: "Dating app fatigue"',
    'Design a shirt: "Swipe right on therapy"',
    'Design a shirt: "Emotionally supported by wings"',
    'Design a shirt: "I survived the roster rotation"',
    'Design a shirt: "Trust fall failure"',
    'Design a shirt: "Zoom shirt, no pants"',
    'Design a shirt: "Reply all survivor"',
    'Design a shirt: "Passive aggressive email champion"',
    'Design a shirt: "LinkedIn vs reality"',
    'Design a shirt: "Cover letter by ChatGPT"',
    'Design a shirt: "Performance review pending"',
    'Design a shirt: "Corporate retreat escapee"',
    'Design a shirt: "Open bar closed heart"',
    'Design a shirt: "Wedding crasher energy"',
    'Design a shirt: "Divorce party MVP"',
    'Design a shirt: "Gender reveal arsonist (jk)"',
    'Design a shirt: "Funeral selfie banned"',
    'Design a shirt: "Family reunion dodgeball champ"',
    'Design a shirt: "Thanksgiving politics refugee"',
    'Design a shirt: "New Year same mistakes"',
    'Design a shirt: "Valentine\'s for one"',
    'Design a shirt: "Halloween emotional damage"',
    'Design a shirt: "Easter egg hunt for red flags"',
    'Design a shirt: "Fourth of July bad texts"',
    'Design a shirt: "Memorial Day remember your ex"',
    'Design a shirt: "Labor Day no labor"',
    'Design a shirt: "Columbus Day lost again"',
    'Design a shirt: "Presidents Day questionable choices"',
    'Design a shirt: "MLK dream deferred"',
    'Design a shirt: "Groundhog saw my shadow"',
    'Design a shirt: "Pi day irrational"',
    'Design a shirt: "May the fourth be with your ex"',
    'Design a shirt: "Cinco de drinko"',
    'Design a shirt: "Star Wars prequel apologist"',
    'Design a shirt: "Marvel roster drama"',
    'Design a shirt: "Anime protagonist delusion"',
    'Design a shirt: "Gym mirror selfie offender"',
    'Design a shirt: "Protein shake crybaby"',
    'Design a shirt: "Yoga pants philosopher"',
    'Design a shirt: "Meditation app uninstaller"',
    'Design a shirt: "Silent retreat loud snorer"',
    'Design a shirt: "Karaoke danger zone"',
    'Design a shirt: "Drunk text archivist"',
    'Design a shirt: "Screenshot criminal"',
    'Design a shirt: "Left on read legend"',
    'Design a shirt: "Typing bubble liar"',
    'Design a shirt: "Close friends traitor"',
    'Design a shirt: "Story view investigator"',
    'Design a shirt: "DM slide athlete"',
    'Design a shirt: "Soft boy hard times"',
    'Design a shirt: "Rizz deficit disorder"',
    'Design a shirt: "Ick immune system weak"',
    'Design a shirt: "No cap all lies"',
    'Design a shirt: "Slay (pending review)"',
    'Design a shirt: "Brain rot PhD"',
    'Design a shirt: "Meme lord degree"',
    'Design a shirt: "Shitposting is my cardio"',
    'Design a shirt: "Algorithm victim"',
    'Design a shirt: "Doomscroll champion"',
    'Design a shirt: "Snooze button Olympian"',
    'Design a shirt: "3am philosopher"',
    'Design a shirt: "Gas station gourmet"',
    'Design a shirt: "Microwave chef"',
    'Design a shirt: "Air fryer cult member"',
    'Design a shirt: "Ramen sommelier"',
    'Design a shirt: "Cereal for dinner again"',
    'Design a shirt: "Pizza rolls prophet"',
    'Design a shirt: "Hot pocket lava mouth"',
    'Design a shirt: "Taco Tuesday mandatory"',
    'Design a shirt: "Wing sauce firefighter"',
    'Design a shirt: "Beer pong diplomat"',
    'Design a shirt: "Flip cup philosopher"',
    'Design a shirt: "Jungle juice scientist"',
    'Design a shirt: "Red cup tower architect"',
    'Design a shirt: "Keg stand record holder"',
    'Design a shirt: "Mimosa tower engineer"',
    'Design a shirt: "Espresso martini trust issues"',
    'Design a shirt: "Tequila memory eraser"',
    'Design a shirt: "Whiskey neat regrets"',
    'Design a shirt: "Wine mom at 22"',
    'Design a shirt: "Hold my beer famous last words"',
    'Design a shirt: "Designated driver (reluctant)"',
    'Design a shirt: "Uber surge victim"',
    'Design a shirt: "Parking ticket speedrun"',
    'Design a shirt: "Roommate chore chart ignorer"',
    'Design a shirt: "Security deposit evaporated"',
    'Design a shirt: "Landlord\'s favorite nightmare"',
    'Design a shirt: "Plant killer certified"',
    'Design a shirt: "Goldfish outlived my ex"',
    'Design a shirt: "Dog ate my dignity"',
    'Design a shirt: "Cat knocked over my drink"',
    'Design a shirt: "Emotionally supported by dog"',
]

DEBATE = [
    "Debate: Is a hot dog a sandwich?",
    "Debate: Does pineapple belong on pizza?",
    "Debate: Is cereal a soup?",
    "Debate: Is water wet?",
    "Debate: Should toilet paper hang over or under?",
    "Debate: Is a taco a sandwich?",
    "Debate: Are boneless wings just chicken nuggets?",
    "Debate: Is Die Hard a Christmas movie?",
    "Debate: Is a burger a sandwich?",
    "Debate: Milk first or cereal first?",
    "Debate: Is a burrito a wrap or a tube sandwich?",
    "Debate: Is listening to audiobooks 'reading'?",
    "Debate: Is a straw one hole or two holes?",
    "Debate: One horse-sized duck or 100 duck-sized horses?",
    "Debate: Is it okay to recline your seat on a plane?",
    "Debate: Is clapping when the plane lands cringe?",
    "Debate: Is texting 'k' rude?",
    "Debate: Is it worse to be late or leave early?",
    "Debate: Should adults sleep with stuffed animals?",
    "Debate: Is wearing sunglasses indoors acceptable?",
    "Debate: Is brunch just late breakfast for rich people?",
    "Debate: Is a Pop-Tart a ravioli?",
    "Debate: Is almond milk really milk?",
    "Debate: Is a calzone a folded pizza?",
    "Debate: Is dipping fries in a milkshake acceptable?",
    "Debate: Is it worse to ghost or leave on read?",
    "Debate: Toilet seat up or down?",
    "Debate: Pajama pants in public — yes or no?",
    "Debate: Is cereal better at night?",
    "Debate: Is it okay to eat pizza with a fork?",
    "Debate: Is a quesadilla grilled cheese?",
    "Debate: Is a smoothie a cold soup?",
    "Debate: Is a muffin just breakfast cake?",
    "Debate: Would you date someone who claps on landing?",
    "Debate: Is 'we should hang soon' a real plan?",
    "Debate: Is soft launch cowardly or smart?",
    "Debate: Is being 'exclusive' the same as dating?",
    "Debate: Should you meet the roster before dating?",
    "Debate: Is liking an ex's photo cheating?",
    "Debate: Is drunk texting forgivable?",
    "Debate: Is the ick fair or petty?",
    "Debate: Is rizz innate or learned?",
    "Debate: Is main character energy annoying?",
    "Debate: Is delulu ever the solulu?",
    "Debate: Should read receipts be illegal?",
    "Debate: Is finsta more real than main?",
    "Debate: Is posting your partner soft launch or hard launch?",
    "Debate: Is 'no cap' still cool?",
    "Debate: Is ghosting ever justified?",
    "Debate: Is a situationship better than nothing?",
    "Debate: Should friends date exes ever?",
    "Debate: Is dating a friend's ex always wrong?",
    "Debate: Is a roster ethical?",
    "Debate: Is cheating worse than lying?",
    "Debate: Is an emotional affair cheating?",
    "Debate: Should you stay friends with an ex?",
    "Debate: Is closure real or a myth?",
    "Debate: Is love at first sight real?",
    "Debate: Is soulmate talk cringe?",
    "Debate: Is astrology a dealbreaker?",
    "Debate: Is politics a first-date topic?",
    "Debate: Is religion a dealbreaker?",
    "Debate: Is height preference shallow?",
    "Debate: Is money talk on date one okay?",
    "Debate: Is splitting the bill always fair?",
    "Debate: Should the person who asked pay?",
    "Debate: Is a coffee date low effort?",
    "Debate: Is dinner too formal for a first date?",
    "Debate: Is a movie date bad for talking?",
    "Debate: Is mini golf the perfect date?",
    "Debate: Is bowling underrated for dates?",
    "Debate: Is arcade date better than bar date?",
    "Debate: Is bar date too cliché?",
    "Debate: Is house party a good first date?",
    "Debate: Is double date a good idea?",
    "Debate: Is group date less pressure?",
    "Debate: Is Vegas a good place to meet someone?",
    "Debate: Is spring break romance real?",
    "Debate: Is vacation fling worth it?",
    "Debate: Is long distance ever worth it?",
    "Debate: Is age gap always a red flag?",
    "Debate: Is dating older wiser or weirder?",
    "Debate: Is dating younger a red flag?",
    "Debate: Is office romance always bad?",
    "Debate: Is dating a coworker fireable?",
    "Debate: Is dating in the friend group doomed?",
    "Debate: Is hookup culture ruining romance?",
    "Debate: Is waiting for marriage outdated?",
    "Debate: Is monogamy natural?",
    "Debate: Is open relationship valid?",
    "Debate: Is polyamory enlightened or messy?",
    "Debate: Is marriage still worth it?",
    "Debate: Is a wedding worth the debt?",
    "Debate: Is eloping smarter than a big wedding?",
    "Debate: Is a prenup unromantic or smart?",
    "Debate: Should you live together before marriage?",
    "Debate: Is moving in too fast?",
    "Debate: Is sharing passwords healthy?",
    "Debate: Is checking a partner's phone ever okay?",
    "Debate: Is jealousy a sign of caring?",
    "Debate: Is fighting healthy in relationships?",
    "Debate: Is silent treatment abuse?",
    "Debate: Is love bombing real?",
    "Debate: Is breadcrumbing cruel?",
    "Debate: Is benching worse than ghosting?",
    "Debate: Is zombie-ing forgivable?",
    "Debate: Is orbiting creepy?",
    "Debate: Is slow fade worse than ghost?",
    "Debate: Is DTR talk necessary?",
    "Debate: Is 'talking' a real stage?",
    "Debate: Is being 'complicated' an excuse?",
    "Debate: Is hot girl summer inclusive?",
    "Debate: Is cuffing season real?",
    "Debate: Is winter boyfriend a thing?",
    "Debate: Is summer roster ethical?",
    "Debate: Is back-to-school reset real?",
    "Debate: Is New Year's kiss mandatory?",
    "Debate: Is Valentine's Day a scam?",
    "Debate: Is Galentine's better than Valentine's?",
    "Debate: Is Halloween couple costume peak cringe?",
    "Debate: Is matching PJs cute or cursed?",
    "Debate: Is pet naming a relationship milestone?",
    "Debate: Is meeting parents scarier than meeting friends?",
    "Debate: Is meeting friends scarier than parents?",
    "Debate: Is Instagram official necessary?",
    "Debate: Is deleting dating apps a milestone?",
    "Debate: Is keeping apps while dating shady?",
    "Debate: Is still on apps while exclusive cheating?",
    "Debate: Is talking to others while exclusive cheating?",
    "Debate: Is flirting cheating?",
    "Debate: Is following thirst traps cheating?",
    "Debate: Is subscribing to OnlyFans cheating?",
    "Debate: Is watching porn cheating?",
    "Debate: Is having a work spouse okay?",
    "Debate: Is best friend of opposite sex okay?",
    "Debate: Is strip club attendance cheating?",
    "Debate: Is bachelor party lap dance cheating?",
    "Debate: Is kiss on cheek cheating?",
    "Debate: Is kiss on New Year's cheating if taken?",
    "Debate: Is drunk kiss forgivable?",
    "Debate: Is one-time mistake forgivable?",
    "Debate: Is once a cheater always a cheater?",
    "Debate: Should cheaters get second chances?",
    "Debate: Is revenge cheating justified?",
    "Debate: Is breakup sex a bad idea?",
    "Debate: Is makeup sex healthy?",
    "Debate: Is blocking an ex mature or petty?",
    "Debate: Is staying unblocked weak?",
    "Debate: Is liking every post stalking?",
    "Debate: Is watching stories stalking?",
    "Debate: Is driving by their house unhinged?",
    "Debate: Is showing up unannounced ever romantic?",
    "Debate: Is grand gesture after ghosting manipulative?",
    "Debate: Is public proposal pressure unfair?",
    "Debate: Is promposal energy cringe at 25?",
    "Debate: Is love letter outdated or romantic?",
    "Debate: Is voice note romance real?",
    "Debate: Are good morning texts necessary?",
    "Debate: Is double texting desperate?",
    "Debate: Is triple texting unforgivable?",
    "Debate: Is waiting three hours to reply playing games?",
    "Debate: Is playing hard to get effective?",
    "Debate: Is being too available unattractive?",
    "Debate: Is mystery attractive?",
    "Debate: Is honesty always best on dates?",
    "Debate: Is oversharing on date one bad?",
    "Debate: Is trauma dump on date one a red flag?",
    "Debate: Is therapy brag attractive?",
    "Debate: Is gym selfie on profile cringe?",
    "Debate: Is fish pic the worst profile photo?",
    "Debate: Is group photo as first pic deceptive?",
    "Debate: Is sunglasses in every pic suspicious?",
    "Debate: Is height lying on apps common?",
    "Debate: Is age lying on apps forgivable?",
    "Debate: Is catfishing ever accidental?",
    "Debate: Is using old photos lying?",
    "Debate: Is using filters lying?",
    "Debate: Is FaceTune on profiles ethical?",
    "Debate: Is AI photos on dating apps fraud?",
    "Debate: Is LinkedIn stalking before a date okay?",
    "Debate: Is Googling a date before meeting normal?",
    "Debate: Is background check before dating extreme?",
    "Debate: Is asking for socials on date one okay?",
    "Debate: Is asking for phone number vs app better?",
    "Debate: Is moving to text too fast?",
    "Debate: Is Snapchat streak a relationship?",
    "Debate: Is being left on delivered worse than read?",
    "Debate: Is 'wyd' a lazy text?",
    "Debate: Is 'u up?' ever romantic?",
    "Debate: Is voice memo at 2am romantic or scary?",
    "Debate: Is playlist as love language valid?",
    "Debate: Is sharing Spotify wrapped too intimate?",
    "Debate: Is sharing Netflix password commitment?",
    "Debate: Is sharing Apple ID too far?",
    "Debate: Is location sharing healthy?",
    "Debate: Is Find My friends stalking?",
    "Debate: Is Life360 for couples toxic?",
    "Debate: Is a shared Notes app love language?",
    "Debate: Is a shared camera roll cute?",
    "Debate: Is couple TikTok account cringe?",
    "Debate: Is posting your partner every day too much?",
    "Debate: Is never posting your partner suspicious?",
    "Debate: Is hiding a partner a red flag?",
    "Debate: Is a secret relationship valid?",
    "Debate: Is dating multiple people without labels okay?",
    "Debate: Is labels talk on date three too soon?",
    "Debate: Is meeting the roster before labels insane?",
    "Debate: Is 'let's see where it goes' an excuse?",
    "Debate: Is 'I'm not ready' always a lie?",
    "Debate: Is 'it's not you it's me' ever true?",
    "Debate: Is breakup because of timing valid?",
    "Debate: Is the right person wrong time real?",
    "Debate: Is staying for potential a mistake?",
    "Debate: Is settling worse than being alone?",
    "Debate: Is being single at 25 a crisis?",
    "Debate: Is being single at 30 freedom or failure?",
    "Debate: Is marriage by 30 a goal?",
    "Debate: Is kids by 30 pressure real?",
    "Debate: Is childfree dating harder?",
    "Debate: Is wanting kids a dealbreaker?",
    "Debate: Is not wanting kids selfish?",
    "Debate: Is pet parenting replacement for kids?",
    "Debate: Is dog profile pic attractive?",
    "Debate: Is hating dogs a dealbreaker?",
    "Debate: Is cat person vs dog person real divide?",
    "Debate: Is allergies a valid breakup reason?",
    "Debate: Is snoring a dealbreaker?",
    "Debate: Is different sleep schedules doomed?",
    "Debate: Is thermostat war relationship killer?",
    "Debate: Is blanket hogging grounds for war?",
    "Debate: Is starfish sleeper selfish?",
    "Debate: Is cuddling all night realistic?",
    "Debate: Is separate blankets the answer?",
    "Debate: Is separate bedrooms healthy?",
    "Debate: Is sleeping together necessary?",
    "Debate: Is morning breath test of true love?",
    "Debate: Is brushing teeth together peak intimacy?",
    "Debate: Is showering together efficient or awkward?",
    "Debate: Is peeing with door open too far?",
    "Debate: Is bathroom privacy necessary in couples?",
    "Debate: Is passing gas in front of partner milestone?",
    "Debate: Is dutch oven prank relationship ender?",
    "Debate: Is fart joke humor immature?",
    "Debate: Is toilet humor on date one bad?",
    "Debate: Is sarcasm attractive or annoying?",
    "Debate: Is dark humor a green flag?",
    "Debate: Is no humor a dealbreaker?",
    "Debate: Is laughing at your own jokes charming?",
    "Debate: Is being too serious on dates bad?",
    "Debate: Is being the funny one in couple exhausting?",
    "Debate: Is being the hot one enough?",
    "Debate: Is being the smart one enough?",
    "Debate: Is being the rich one enough?",
    "Debate: Is being the chill one boring?",
    "Debate: Is being the chaotic one fun or tiring?",
    "Debate: Is dating your opposite sustainable?",
    "Debate: Is dating your clone boring?",
    "Debate: Is dating someone like your ex a pattern?",
    "Debate: Is having a type limiting?",
    "Debate: Is ignoring red flags because they're hot forgivable?",
    "Debate: Is dating fixer-upper projects smart?",
    "Debate: Is dating projects doomed?",
    "Debate: Is you can't change people true?",
    "Debate: Is love enough to make it work?",
    "Debate: Is compatibility more important than chemistry?",
    "Debate: Is chemistry more important than compatibility?",
    "Debate: Is slow burn better than instant spark?",
    "Debate: Is love at first swipe real?",
    "Debate: Is dating app fatigue real?",
    "Debate: Is deleting apps and meeting IRL better?",
    "Debate: Is meeting at a bar romantic?",
    "Debate: Is meeting through friends better?",
    "Debate: Is meeting at work cursed?",
    "Debate: Is meeting on vacation doomed?",
    "Debate: Is meeting at gym cliché?",
    "Debate: Is meeting at coffee shop movie trope?",
    "Debate: Is meeting at wedding destined?",
    "Debate: Is dating the bride's cousin off limits?",
    "Debate: Is dating the groom's sister chaos?",
    "Debate: Is dating the DJ at the wedding valid?",
    "Debate: Is dating the bartender valid?",
    "Debate: Is tipping the bartender flirting?",
    "Debate: Is free drinks flirting?",
    "Debate: Is buying shots for strangers harassment?",
    "Debate: Is buying shots for friends loyalty?",
    "Debate: Is buying shots for your ex pathetic?",
    "Debate: Is crying at the bar after breakup allowed?",
    "Debate: Is karaoke drunk confession romantic?",
    "Debate: Is drunk 'I love you' valid?",
    "Debate: Is sober 'I love you' scarier?",
    "Debate: Is saying I love you first weak?",
    "Debate: Is waiting for them to say it first smart?",
    "Debate: Is not saying it back a breakup?",
    "Debate: Is loving someone who doesn't love you back noble?",
    "Debate: Is unrequited love romantic or sad?",
    "Debate: Is friend zone real?",
    "Debate: Is nice guy syndrome real?",
    "Debate: Is bad boy attraction explainable?",
    "Debate: Is dating assholes a phase?",
    "Debate: Is dating nice people boring?",
    "Debate: Is green flag boring?",
    "Debate: Is red flag exciting?",
    "Debate: Is dating stable person underrated?",
    "Debate: Is dating chaotic person addictive?",
    "Debate: Is therapy the new six-pack?",
    "Debate: Is emotional intelligence attractive?",
    "Debate: Is communication skill sexy?",
    "Debate: Is vulnerability attractive?",
    "Debate: Is crying in front of partner strength?",
    "Debate: Is never crying suspicious?",
    "Debate: Is stoic partner better?",
    "Debate: Is expressive partner exhausting?",
    "Debate: Is anxious attachment fixable?",
    "Debate: Is avoidant attachment a red flag?",
    "Debate: Is secure attachment rare?",
    "Debate: Is attachment style destiny?",
    "Debate: Is love language talk helpful?",
    "Debate: Is acts of service love language best?",
    "Debate: Is gifts love language materialistic?",
    "Debate: Is words of affirmation needy?",
    "Debate: Is physical touch love language enough?",
    "Debate: Is quality time love language hardest?",
    "Debate: Is planning dates men's job?",
    "Debate: Is splitting planning fair?",
    "Debate: Is always planning exhausting?",
    "Debate: Is never planning lazy?",
    "Debate: Is surprise date romantic?",
    "Debate: Is surprise visit romantic?",
    "Debate: Is surprise proposal fair?",
    "Debate: Is public breakup worse than public proposal?",
    "Debate: Is breaking up over text ever okay?",
    "Debate: Is breaking up over phone cowardly?",
    "Debate: Is breaking up in person mandatory?",
    "Debate: Is ghosting after one date okay?",
    "Debate: Is ghosting after three months evil?",
    "Debate: Is slow fade kinder than ghost?",
    "Debate: Is honest rejection kinder?",
    "Debate: Is 'you're great but not for me' cliché?",
    "Debate: Is staying friends after breakup realistic?",
    "Debate: Is hating ex healthy?",
    "Debate: Is missing ex weakness?",
    "Debate: Is stalking ex socials normal?",
    "Debate: Is dating again immediately healthy?",
    "Debate: Is rebound relationship valid?",
    "Debate: Is revenge body real?",
    "Debate: Is glow up after breakup performative?",
    "Debate: Is posting thirst trap after breakup petty?",
    "Debate: Is dating their friend revenge?",
    "Debate: Is dating their sibling unforgivable?",
    "Debate: Is showing up to their wedding unhinged?",
    "Debate: Is toaster at wedding gift evil?",
    "Debate: Is bringing a date to ex's wedding petty?",
    "Debate: Is wedding hookup with ex's cousin chaos?",
    "Debate: Is open bar at ex's wedding dangerous?",
    "Debate: Is crying at ex's wedding normal?",
    "Debate: Is congratulating ex on engagement fake?",
    "Debate: Is blocking ex at engagement healthy?",
    "Debate: Is attending ex's funeral respect or drama?",
    "Debate: Is dating widower too heavy?",
    "Debate: Is dating divorcee baggage?",
    "Debate: Is dating single parent harder?",
    "Debate: Is not wanting kids with someone who does fair?",
    "Debate: Is ultimatum about marriage fair?",
    "Debate: Is waiting five years for proposal foolish?",
    "Debate: Is proposing without ring okay?",
    "Debate: Is expensive ring necessary?",
    "Debate: Is lab diamond acceptable?",
    "Debate: Is moissanite insulting?",
    "Debate: Is wedding size about love or ego?",
    "Debate: Is destination wedding selfish?",
    "Debate: Is courthouse wedding underrated?",
    "Debate: Is big wedding worth debt?",
    "Debate: Is honeymoon immediately necessary?",
    "Debate: Is joint bank account necessary?",
    "Debate: Is keeping finances separate smart?",
    "Debate: Is financial transparency required?",
    "Debate: Is secret debt dealbreaker?",
    "Debate: Is credit score compatibility real?",
    "Debate: Is student loan debt partner's problem?",
    "Debate: Is paying for partner's debt love?",
    "Debate: Is lending money to partner bad?",
    "Debate: Is moving for partner's job worth it?",
    "Debate: Is long distance for career worth it?",
    "Debate: Is choosing city over partner selfish?",
    "Debate: Is choosing partner over city romantic?",
    "Debate: Is ultimatum about moving fair?",
    "Debate: Is breaking up over location valid?",
    "Debate: Is right person wrong city real?",
    "Debate: Is dating in small town harder?",
    "Debate: Is dating in big city overwhelming?",
    "Debate: Is dating pool in college best?",
    "Debate: Is post-grad dating harder?",
    "Debate: Is dating after 30 harder for men or women?",
    "Debate: Is dating market unfair?",
    "Debate: Is being picky lonely?",
    "Debate: Is lowering standards settling?",
    "Debate: Is having standards elitist?",
    "Debate: Is checklist dating bad?",
    "Debate: Is soulmate checklist cringe?",
    "Debate: Is manifesting a partner real?",
    "Debate: Is astrology compatibility nonsense?",
    "Debate: Is MBTI compatibility nonsense?",
    "Debate: Is enneagram compatibility nonsense?",
    "Debate: Is love language compatibility nonsense?",
    "Debate: Is chemistry enough for marriage?",
    "Debate: Is shared values enough without spark?",
    "Debate: Is spark enough without shared values?",
    "Debate: Is best friend partner ideal?",
    "Debate: Is passion necessary long term?",
    "Debate: Is passion doomed to fade?",
    "Debate: Is comfortable love underrated?",
    "Debate: Is boring relationship stable or dead?",
    "Debate: Is fighting mean incompatible?",
    "Debate: Is never fighting suspicious?",
    "Debate: Is makeup sex toxic?",
    "Debate: Is angry sex toxic?",
    "Debate: Is breakup sex closure?",
    "Debate: Is closure sex myth?",
    "Debate: Is one last time myth?",
    "Debate: Is blocking after bad breakup healthy?",
    "Debate: Is unblocking after six months weak?",
    "Debate: Is drunk text to ex always bad?",
    "Debate: Is happy birthday text to ex okay?",
    "Debate: Is liking ex's engagement photo maturity?",
    "Debate: Is showing up at ex's door cinematic or creepy?",
]

FINISH_SENTENCE = [
    "The best part of waking up is _____",
    "I never leave home without _____",
    "My doctor told me to stop _____",
    "In the future, everyone will _____",
    "The worst part about dating is _____",
    "My group chat is mostly _____",
    "I knew it was a bad idea when _____",
    "My toxic trait is _____",
    "The airport security agent found _____",
    "I regret googling _____",
    "My bank account cries whenever I _____",
    "The wedding toast went wrong when _____",
    "I peaked when _____",
    "My Roman Empire is _____",
    "I would sell my soul for _____",
    "My Uber driver asked me about _____",
    "The group chat exploded when someone sent _____",
    "I knew adulthood hit when I got excited about _____",
    "My most controversial opinion is about _____",
    "The worst thing I googled at 3am was _____",
    "My situationship ended because of _____",
    "My toxic coping mechanism is _____",
    "The red flag I ignored was _____",
    "My villain origin story started with _____",
    "I would fight a bear for _____",
    "The hill I will die on involves _____",
    "My most unhinged purchase was _____",
    "My honest LinkedIn headline would mention _____",
    "The worst text I ever sent said _____",
    "I would delete my search history before anyone sees _____",
    "My love language is secretly _____",
    "The most chaotic thing in my apartment is _____",
    "My group vacation role is always _____",
    "The worst advice I ever followed was about _____",
    "My finsta is just pictures of _____",
    "My roster notes app is titled _____",
    "The last thing I drunk ordered was _____",
    "My spring break scar is named _____",
    "My Vegas story starts with _____",
    "My hangover cure is _____",
    "My pregame ritual is _____",
    "My walk of shame outfit included _____",
    "My 2am DoorDash order was _____",
    "My situationship status is _____",
    "My red flag parade float is _____",
    "My emotional support item is _____",
    "My college major should have been _____",
    "My superlative in the friend group is _____",
    "My autobiography chapter one is called _____",
]

PITCH = [
    "Pitch a startup that delivers regret by drone",
    "Sell invisible socks with a subscription model",
    "Pitch an app that ranks your roster automatically",
    "Convince investors that sleep is optional for Gen Z",
    "Pitch a restaurant where every dish is gas station food",
    "Sell a gym membership for your emotional baggage",
    "Pitch a dating app that notifies your ex when you're online",
    "Convince us to buy bottled air from frat houses",
    "Pitch a theme park based on your group chat",
    "Sell a haunted smart home that only plays Drake",
    "Pitch a cryptocurrency backed by brunch reservations",
    "Convince us that hats for dogs are the future of fashion",
    "Pitch a subscription box of red flags",
    "Sell a meditation app that just plays pregame music",
    "Pitch a wedding venue inside a Waffle House",
    "Convince investors that gas station sushi is upscale",
    "Pitch an Uber pool but for emotional damage",
    "Sell a cologne called '2am Decisions'",
    "Pitch a support group app for chronic roster managers",
    "Convince us to buy a finsta verification badge",
    "Pitch a reality show about your situationships",
    "Sell a hangover clinic that also does therapy",
    "Pitch a dating app where your mom approves matches",
    "Convince us that emotional support red cups are medical devices",
    "Pitch a brewery that names beers after your exes",
    "Sell a smart mirror that roasts your outfit",
    "Pitch a college course in advanced ghosting",
    "Convince investors that walk of shame escorts are essential",
    "Pitch a Vegas chapel with a refund policy",
    "Sell a passport stamp for bad decisions",
    "Pitch a group chat moderation AI with zero tolerance",
    "Convince us that Roman Empire brain scans are wellness",
    "Pitch a tear-free onion that also prevents drunk texting",
    "Sell a loyalty program for bars you've been banned from",
    "Pitch a spring break insurance for dignity",
    "Convince us that protein powder for regret is market-ready",
    "Pitch a karaoke app that only allows breakup songs",
    "Sell a dating profile photo filter called 'Not Catfishing'",
    "Pitch a roommate finder based on chore chart compatibility",
    "Convince investors that emotional support pong tables save lives",
]

TEXT_TRANSFORM = [
    'Translate to Gen Z: "Hello, how are you today?"',
    'Make clickbait: "Local man finds thing"',
    'Passive-aggressive email: "Please submit your report"',
    'Movie tagline: "A man walks into a bar"',
    'Breakup text: "We need to talk"',
    'Legal disclaimer: "Have fun tonight"',
    'Villain monologue: "I just want peace"',
    'Yelp review: "The food was fine"',
    'Conspiracy tweet: "The sky is blue"',
    'TED talk title: "I lost my keys"',
    'Drunk text rewrite: "I miss u"',
    'LinkedIn post: "I got fired"',
    'Wedding toast: "To the happy couple"',
    'Funeral speech: "They lived well"',
    'Tinder bio: "Just ask"',
    'Instagram caption: "Living my best life"',
    'Group chat announcement: "I have news"',
    'Uber driver small talk: "Busy night?"',
    'Mom text: "Call me"',
    'Boss Slack: "Quick sync?"',
    'Roommate note: "Do your dishes"',
    'Ex apology: "I messed up"',
    'Situationship define: "What are we?"',
    'Roster update email: "Weekly standings"',
    'Hangover status: "I am alive"',
    'Pregame hype speech: "Tonight we ride"',
    'Walk of shame press release',
    'Vegas recap blog post',
    'Spring break incident report',
    'Performance review after Vegas',
    'Passive-aggressive RSVP: "Maybe"',
    'Clickbait roster reveal',
    'True crime podcast intro about your texts',
    'Weather alert: situationship incoming',
    'Medical chart: acute ick',
    'Police report: noise complaint at pregame',
    'Airbnb review: "Would not recommend"',
    'Amazon product review: drunk purchase',
    'Spotify playlist title: "Sad boy hours"',
    'Netflix description: your love life',
]

WORD_CHAIN = [
    "Spring break", "Vegas regrets", "Roster chaos", "Group chat", "Red flag",
    "Situationship", "Hangxiety", "Pregame", "Walk of shame", "2am tacos",
    "Finsta drama", "Soft launch", "Hard landing", "Main character", "Delulu",
    "Rizz deficit", "Ick outbreak", "No cap", "Brain rot", "Meme war",
    "Brunch cult", "Gas station sushi", "Uber pool", "Zoom date", "LinkedIn lie",
    "Frat formal", "Beer pong", "Jungle juice", "Karaoke night", "Breakup song",
    "Therapy homework", "Roman Empire", "Toxic trait", "Love language", "Ghost mode",
    "Read receipt", "Left on read", "Screenshot crime", "Drunk text", "DoorDash knight",
    "Credit decline", "Hangover monster", "Protein shake", "Leg day skip", "Gym mirror",
    "College dining", "Finals week", "Group project", "Student loan", "Diploma regret",
    "Job interview", "Performance review", "Corporate retreat", "Open bar", "Wedding crasher",
    "Divorce party", "Gender reveal", "Family reunion", "Thanksgiving fight", "New Year kiss",
    "Valentine alone", "Halloween costume", "Costco sheet cake", "Vegas chapel", "Bachelor party",
    "Roster rotation", "Ex energy", "Closure myth", "Rebound season", "Glow up",
    "Thirst trap", "Soft boy", "Chaos agent", "Emotional support", "Bad decision",
    "Questionable life", "Spite fueled", "Powered by anxiety", "Low battery", "Do not perceive",
]

RANK = [
    "Rank best to worst: Pizza toppings — Pineapple, Pepperoni, Mushroom, Anchovy, Olives",
    "Rank best to worst: Hangover cures — Water, Greasy food, More drinks, Sleep, Denial",
    "Rank best to worst: Date ideas — Movies, Hiking, Bar, Mini golf, Museum",
    "Rank best to worst: Red flags — Lying, Roster, Love bombing, Bad texter, No job",
    "Rank best to worst: Drunk foods — Pizza, Tacos, Ramen, Nuggets, Cereal",
    "Rank best to worst: Texting sins — Ghosting, Left on read, K, Voice note at 3am, Screenshot",
    "Rank best to worst: Party games — Beer pong, Kings, Never have I ever, Truth or dare, Monopoly",
    "Rank best to worst: Breakup methods — Ghost, Text, Phone, In person, Mutual friend",
    "Rank best to worst: Social apps — Group chat, Stories, Dating app, LinkedIn, Twitter",
    "Rank best to worst: Spring break destinations — Beach, Vegas, Cruise, Ski, Home",
    "Rank best to worst: Roommate crimes — Dishes, Loud sex, Thermostat, Guests, Stealing food",
    "Rank best to worst: Wedding disasters — Open bar, Ex shows up, Speech, Weather, Cake",
    "Rank best to worst: Superpowers for dating — Mind reading, Invisibility, Time travel, Rizz, Money",
    "Rank best to worst: Apology gifts — Flowers, Food, Jewelry, Handwritten note, Nothing",
    "Rank best to worst: First date outfits — Too casual, Too formal, Gym clothes, Hat indoors, Perfect",
    "Rank best to worst: College majors for dating — Psych, Business, Theater, Engineering, Undecided",
    "Rank best to worst: Pregame drinks — Beer, Vodka soda, Tequila, Wine, Jungle juice",
    "Rank best to worst: Excuses for canceling — Sick, Tired, Ex drama, Forgot, Honest",
    "Rank best to worst: Profile photos — Gym selfie, Fish, Group pic, Sunglasses only, Dog pic",
    "Rank best to worst: Love languages — Words, Touch, Gifts, Acts, Quality time",
    "Rank best to worst: Pet choices — Dog, Cat, None, Reptile, Roommate's pet",
    "Rank best to worst: Morning routines — Snooze, Coffee, Exercise, Skip breakfast, Scroll phone",
    "Rank best to worst: Vacation spots — Beach, Mountains, City, Camping, Staycation",
    "Rank best to worst: Movie genres — Comedy, Horror, Rom-com, Documentary, Action",
    "Rank best to worst: Seasons — Summer, Fall, Winter, Spring",
    "Rank best to worst: Ice cream flavors — Vanilla, Chocolate, Strawberry, Mint chip, Weird",
    "Rank best to worst: Coffee orders — Black, Latte, Cold brew, Frappuccino, Gas station",
    "Rank best to worst: Chip brands — Classic, Spicy, BBQ, Weird flavor, Off-brand",
    "Rank best to worst: Group trip roles — Planner, Driver, Chef, Chaos agent, Photographer",
    "Rank best to worst: Fantasy football punishments — Tattoo, Humiliation, Money, Beer, Nothing",
    "Rank best to worst: Bar types — Dive, Club, Sports, Rooftop, Wine",
    "Rank best to worst: Texting styles — Paragraph, One word, Memes only, Voice notes, Dry",
    "Rank best to worst: Apology styles — Flowers, Groveling, Joke, Space, Gift card",
    "Rank best to worst: Flirting techniques — Compliment, Tease, Meme, Eye contact, Terrible joke",
    "Rank best to worst: Party arrival times — Early, On time, Fashionably late, After pregame, Never",
    "Rank best to worst: Uber ratings you'd deserve — 5, 4, 3, 2, Banned",
    "Rank best to worst: Excuses for being late — Traffic, Overslept, Ex, Lost keys, No excuse",
    "Rank best to worst: College dining — Pizza, Burgers, Salad bar, Mystery meat, Cereal",
    "Rank best to worst: Shot types — Tequila, Whiskey, Vodka, Jäger, Unknown",
    "Rank best to worst: Karaoke songs — Power ballad, Rap, Disney, Breakup song, Screaming",
    "Rank best to worst: Halloween costumes — Sexy, Funny, Lazy, Couple, Offensive",
    "Rank best to worst: New Year's resolutions — Gym, Save money, Date more, Drink less, Lie",
    "Rank best to worst: Valentine's gifts — Chocolate, Flowers, Jewelry, Experience, Nothing",
    "Rank best to worst: Breakup comfort — Friends, Food, Gym, Rebound, Isolation",
    "Rank best to worst: Study snacks — Chips, Fruit, Candy, Coffee, Nothing",
    "Rank best to worst: Road trip snacks — Chips, Jerky, Candy, Fruit, Fast food",
    "Rank best to worst: Gym music — Rap, EDM, Pop, Podcast, Silence",
    "Rank best to worst: Shower thoughts quality — Deep, Funny, Horny, Anxious, Nonsense",
    "Rank best to worst: 3am activities — Text ex, DoorDash, Scroll, Cry, Sleep",
    "Rank best to worst: Sunday scaries fixes — Brunch, Gym, Sleep, Denial, Work prep",
    "Rank best to worst: Monday moods — Dead, Coffee, Motivated, Hungover, Calling in sick",
    "Rank best to worst: Group chat notification styles — Mute, All messages, Mentions only, Leave",
    "Rank best to worst: Dating app openers — Hey, Pun, Question, Compliment, Unhinged",
    "Rank best to worst: Reasons to swipe right — Face, Bio, Dog, Job, Vibes",
    "Rank best to worst: Reasons to unmatch — Bad opener, Rude, Boring, Red flag, Ghosted",
    "Rank best to worst: Party fouls — Spill, Fight, Vomit, Break thing, Pass out",
    "Rank best to worst: Hangover symptoms — Headache, Nausea, Anxiety, Regret, All above",
    "Rank best to worst: Drunk personality types — Happy, Sad, Angry, Flirty, Sleepy",
    "Rank best to worst: Things to lose at a party — Phone, Dignity, Jacket, Friend, Ride home",
    "Rank best to worst: Things found in a frat couch — Change, Crumbs, Mystery, Phone, Dignity",
    "Rank best to worst: Spring break regrets — Tattoo, Ex, Video, Sunburn, Bank account",
    "Rank best to worst: Vegas regrets — Wedding, Tattoo, Losses, Video, All",
    "Rank best to worst: Text tones — Friendly, Flirty, Passive aggressive, Desperate, Unhinged",
]

SORT = [
    "Sort oldest to newest: Moon landing, WW2 ends, First iPhone, Internet public, Berlin Wall falls",
    "Sort smallest to largest: Mouse, Human, Horse, Elephant, Blue whale",
    "Sort shortest to tallest: Statue of Liberty, Eiffel Tower, Empire State, Burj Khalifa",
    "Sort least to most embarrassing: Like ex photo, Drunk text, Public cry, Walk of shame, Vegas livestream",
    "Sort least to most red flag: Bad texter, Roster, Lies, Cheating, Love bombing",
    "Sort cheapest to most expensive: Ramen, Fast food, Brunch, Steak dinner, Vegas night",
    "Sort least to most chaotic: Coffee date, Bar date, House party, Vegas, Spring break",
    "Sort least to most commitment: Talking, Exclusive, Meet parents, Move in, Engaged",
    "Sort least to most drunk: Sober, Buzzed, Drunk, Blackout, Hospital",
    "Sort least to most likely to ghost: Best friend, Situationship, Tinder match, Ex, Therapist",
    "Sort least to most painful: Paper cut, Breakup, Hangovers, Student loans, Stepping on Lego",
    "Sort least to most iconic: First kiss, First love, First heartbreak, First Vegas trip, First roster",
    "Sort least to most cursed: Normal date, Double date with ex, Vegas wedding, Group chat leak, Finsta exposed",
    "Sort least to most respectable: Ghosting, Slow fade, Honest talk, Closure sex, Block everywhere",
    "Sort least to most expensive mistake: Fast food, Uber surge, Drunk Amazon, Vegas table, Wedding",
    "Sort least to most likely text at 2am: Mom, Boss, Ex, Whole roster, Group chat manifesto",
    "Sort least to most toxic: Forgot birthday, Roster, Lied, Cheated, Public humiliation",
    "Sort least to most impressive: Cooked dinner, Planned date, Remembered detail, Grand gesture, Vegas surprise",
    "Sort least to most unhinged: Double text, Drunk call, Show up unannounced, Airport chase, Wedding objection",
    "Sort least to most believable excuse: Traffic, Sick, Phone died, Alien abduction, 'I forgot humans exist'",
    "Sort oldest to newest: First iPhone, Instagram launch, TikTok boom, COVID lockdown, ChatGPT hype",
    "Sort smallest to largest: Studio apartment, House, Mansion, Campus, Vegas hotel suite",
    "Sort cheapest to priciest: Water, Coffee, Brunch, Steak, Bottle service",
    "Sort least to most romantic: U up text, Good morning text, Handwritten note, Surprise trip, Proposal",
    "Sort least to most awkward: Elevator silence, Ex at party, Parent meeting, Work flirt, Doctor question",
    "Sort least to most likely to go viral: Bad take, Dance fail, Rant video, Proposal fail, Livestream incident",
    "Sort least to most respectable job: Influencer, Bartender, Teacher, Engineer, Surgeon",
    "Sort least to most dangerous party activity: Darts, Pool, Pong, Flip cup, Roof",
    "Sort least to most elite snack: Chips, Trail mix, Charcuterie, Sushi, Caviar",
    "Sort least to most iconic duo: Peanut butter jelly, Burger fries, Tequila lime, Coffee donut, You and bad decisions",
    "Sort least to most stressful notification: Mom, Boss, Bank, Ex, 'We need to talk'",
    "Sort least to most cursed date venue: Movie, Fancy dinner, Your ex's workplace, Family BBQ, Vegas chapel",
    "Sort least to most forgiving: Best friend, Mom, Dog, Bank, IRS",
    "Sort least to most likely comeback: Gym, Glow up, New partner photo, Success post, Grammy speech shade",
    "Sort least to most dramatic breakup location: Text, Car, Restaurant, Wedding, Super Bowl party",
    "Sort least to most effective apology: Sorry emoji, Flowers, Groveling, Change behavior, Time travel",
    "Sort least to most chaotic group trip member: Planner, Snorer, DJ, Food thief, 'I know a shortcut' guy",
    "Sort least to most respectable drunk purchase: Snacks, Shoes, Pet, Tattoo, Boat",
    "Sort least to most likely to start drama: Mention ex, Split bill wrong, Playlist choice, Board game, Monopoly",
    "Sort least to most elite hangover meal: Crackers, Greasy spoon, Pho, Full English, IV drip brunch",
    "Sort least to most trustworthy: Dog, Best friend, Therapist, Weather app, Your ex 'just checking in'",
    "Sort least to most expensive hobby: Reading, Gaming, Golf, Skiing, Crypto",
    "Sort least to most iconic college experience: All-nighter, Party, Spring break, Internship, Forgot class exists",
    "Sort least to most spicy food take: Ketchup on eggs, Ranch on pizza, Pineapple pizza, Milk on spicy, Gas station sushi",
    "Sort least to most elite flex: New car, Vacation pic, Engagement, Paid off loans, Slept eight hours",
    "Sort least to most likely to get you canceled: Old tweet, Bad joke, Costume, Political take, Group chat leak",
    "Sort least to most effective wingman move: Introduce, Distract ex, Pay tab, Uber home, Fake emergency",
    "Sort least to most respectable sleep schedule: 10pm, Midnight, 2am, 4am, 'What is sleep'",
    "Sort least to most elite date flex: Split bill, Tip well, Remember order, Plan surprise, Know the chef",
    "Sort least to most chaotic wedding guest: Quiet aunt, Drunk uncle, Ex, Plus one stranger, DJ",
    "Sort least to most believable plot twist: Secret twin, Long lost sibling, In witness protection, AI boyfriend, It was a dream",
    "Sort least to most respectable superpower: Flight, Invisibility, Mind reading, Time travel, Unlimited rizz",
    "Sort least to most likely group chat message: Meme, Plans, Drama, Voice note, 47-message rant",
    "Sort least to most elite comeback to ghosting: Block, Post thirst trap, Date friend, Live well, Text 'lol'",
    "Sort least to most chaotic Vegas hour: Check in, Dinner, Show, Table, Sunrise regret",
    "Sort least to most respectable reason to leave party: Tired, Work, Ride, Bad vibe, Found better party",
    "Sort least to most effective flirting: Eye contact, Compliment, Joke, Touch arm, Show up with food",
    "Sort least to most iconic bad decision: Second drink, Text ex, Double down blackjack, Get tattoo, Get married",
    "Sort least to most elite roommate quality: Quiet, Clean, Pays rent, Shares snacks, Disappears when you have a date",
    "Sort least to most chaotic family dinner topic: Weather, Politics, Dating life, Career, Why still single",
]

BRACKET = [
    "Best pizza topping", "Best superpower", "Best vacation spot", "Best movie genre",
    "Best season", "Best hangover food", "Best house pet", "Best party game",
    "Best drunk food", "Best dating app opener", "Best breakup song", "Best pregame song",
    "Best red flag excuse", "Best walk of shame outfit", "Best Vegas mistake",
    "Best spring break story type", "Best group chat name theme", "Best finsta content",
    "Best situationship nickname", "Best roster management strategy", "Best apology method",
    "Best college dining option", "Best bar type", "Best karaoke song genre",
    "Best Halloween costume category", "Best New Year's resolution lie",
    "Best Valentine's Day move", "Best text tone", "Best love language",
    "Best roommate quality", "Best road trip snack", "Best gym excuse",
    "Best Sunday scaries fix", "Best 3am decision", "Best meme format",
    "Best thirst trap angle", "Best soft launch method", "Best hard launch disaster",
    "Best ghosting excuse", "Best DTR location", "Best first date activity",
]

ROLE_LABEL = [
    "Who is most likely to survive a zombie apocalypse?",
    "Who gives the best advice?",
    "Who would win in a dance-off?",
    "Who is the best cook?",
    "Who would accidentally start a cult?",
    "Who is most likely to become famous?",
    "Who would die first in a horror movie?",
    "Who sends the riskiest texts?",
    "Who is the biggest chaos agent?",
    "Who would win at poker?",
    "Who is most likely to move abroad on a whim?",
    "Who has the worst taste in partners?",
    "Who would eat expired food 'to test it'?",
    "Who is most likely to get banned from a bar?",
    "Who would become a billionaire or go broke first?",
    "Who is the best at keeping secrets?",
    "Who would spoil a TV show on purpose?",
    "Who is most likely to cry at a commercial?",
    "Who would survive longest on a deserted island?",
    "Who is the worst at directions?",
    "Who is most likely to drunk text the roster?",
    "Who would plan the worst group trip?",
    "Who is most likely to soft launch wrong?",
    "Who would get kicked out of Vegas first?",
    "Who has the worst hangxiety?",
    "Who would eat gas station sushi?",
    "Who is most likely to forget their own birthday?",
    "Who would win a beer pong tournament?",
    "Who is most likely to cry during karaoke?",
    "Who would accidentally propose?",
    "Who is most likely to become a meme?",
    "Who would survive a family dinner best?",
    "Who is most likely to get a tattoo on spring break?",
    "Who would forget their wallet on a date?",
    "Who is most likely to start a bar fight?",
    "Who would be the worst roommate?",
    "Who is most likely to go viral for the wrong reason?",
    "Who would eat the most drunk food?",
    "Who is most likely to sleep through their alarm?",
    "Who would be the best wingman?",
]

TEAMWORK = [
    "Everyone pick a different wire color — exactly one is safe!",
    "Each player must choose a unique number from 1 to 8.",
    "Coordinate: one player says HEADS, another says TAILS.",
    "Pick tools in order without repeating: wrench, hammer, screwdriver, drill.",
    "Assign each player a unique planet: Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus.",
    "One player must type YES while another types NO at the same time.",
    "Each player picks a unique emoji reaction; no duplicates allowed.",
    "Everyone choose a different card suit: hearts, diamonds, clubs, spades.",
    "Pick unique colors: red, blue, green, yellow, purple, orange, pink.",
    "One player says START, another says STOP, another says GO.",
    "Each player selects a unique day of the week.",
    "Assign roles: captain, engineer, medic, pilot — no repeats.",
    "Everyone type a different vowel: A, E, I, O, U.",
    "Pick unique seasons: spring, summer, fall, winter.",
    "Each player picks a different pizza topping to defend.",
    "Assign each player a unique drink: beer, wine, whiskey, vodka, tequila, rum, gin.",
    "One player types BRUNCH, another types DINNER, another LUNCH.",
    "Everyone pick a different red flag to ignore.",
    "Each player chooses a unique excuse for being late.",
    "Assign each player a unique love language.",
    "Pick unique college majors without repeating.",
    "Each player names a different dating app.",
    "Everyone pick a unique hangover cure.",
    "Assign each player a unique superpower.",
    "One player says PREGAME, another AFTERPARTY, another WALK OF SHAME.",
    "Each player picks a unique Vegas mistake.",
    "Everyone choose a different text tone.",
    "Assign each player a unique party foul.",
    "Pick unique karaoke songs without repeating genres.",
    "Each player selects a unique roster nickname.",
    "Everyone pick a different finsta topic.",
    "Assign each player a unique meme format.",
    "One player types SOFT LAUNCH, another HARD LAUNCH.",
    "Each player picks a unique bar type.",
    "Everyone choose a different 3am activity.",
    "Assign each player a unique spring break regret.",
    "Pick unique profile photo types without repeating.",
    "Each player names a different red flag.",
    "Everyone pick a unique breakup method.",
    "Assign each player a unique love song era.",
    "One player says RIZZ, another says ICK, another DELULU.",
    "Each player picks a unique group chat role.",
    "Everyone choose a different drunk personality.",
    "Assign each player a unique apology gift.",
    "Pick unique Halloween costume types.",
    "Each player selects a unique New Year's lie.",
    "Everyone pick a different Sunday scaries fix.",
    "Assign each player a unique Uber rating.",
    "One player types GHOST, another TEXT BACK, another BLOCK.",
    "Each player picks a unique situationship stage.",
]

HIDDEN_TASK = [
    "Type a message containing the word BLUE.",
    "Vote for the player on your left in the next round.",
    "Laugh when anyone says 'definitely'.",
    "Say 'interesting' in your next submission.",
    "Vote for the player with the longest name.",
    "Submit an answer that rhymes with 'cat'.",
    "Include a number in your answer.",
    "Mention food in your submission.",
    "Use all caps in one word of your answer.",
    "Submit the shortest possible answer.",
    "Submit the longest possible answer.",
    "Vote for an answer containing the letter Z.",
    "Type 'trust me' in your submission.",
    "Vote for the middle entry on the list.",
    "Include an animal in your answer.",
    "Mention a drink in your answer.",
    "Use the word 'roster' in your submission.",
    "Vote for whoever submitted first.",
    "Submit an answer with exactly seven words.",
    "Mention Vegas in your answer.",
    "Include a color in your submission.",
    "Vote for the funniest sounding answer.",
    "Type 'no cap' somewhere in your answer.",
    "Mention your ex without using the word ex.",
    "Submit an answer that sounds like a tattoo.",
    "Vote for an answer that mentions pizza.",
    "Use a question mark in your submission.",
    "Mention brunch in your answer.",
    "Vote for the player on your right.",
    "Submit an answer that could be a band name.",
    "Include the word 'chaos' in your answer.",
    "Vote for an answer shorter than five words.",
    "Mention a red flag in your submission.",
    "Type an emoji concept in words only.",
    "Vote for an answer that mentions sleep.",
    "Submit something that sounds like a startup pitch.",
    "Mention a holiday in your answer.",
    "Vote for an answer with alliteration.",
    "Include a job title in your submission.",
    "Mention gas station food in your answer.",
    "Vote for whoever sounds most unhinged.",
    "Submit an answer that could be a finsta caption.",
    "Use the word 'vibe' in your submission.",
    "Vote for an answer mentioning sports.",
    "Mention a phone app in your answer.",
    "Submit an answer that sounds like a Yelp review.",
    "Vote for an answer that mentions family.",
    "Include a weather word in your submission.",
    "Mention karaoke in your answer.",
    "Vote for the second entry on the list.",
]

# True-or-lie: keep only tricky misconceptions + surprising truths (no textbook spam)
KEEP_TRUE_OR_LIE_PATTERNS = [
    re.compile(r"never|not |false|myth|incorrect|blind|three-second|10%|flat", re.I),
    re.compile(r"true|actually|older than|longer than|called a|invented|named after", re.I),
    re.compile(r"war|unicorn|cube|wood|moth|QWERTY|parliament|spoils", re.I),
]

DROP_TRUE_OR_LIE_PATTERNS = [
    re.compile(r"the human body has enough", re.I),
    re.compile(r"the human body has \d+", re.I),
    re.compile(r"the human body produces enough", re.I),
    re.compile(r"the word 'pioneer'", re.I),
    re.compile(r"first video game console was", re.I),
    re.compile(r"the human (heart beats|body has about|body contains|body sheds|body makes)", re.I),
    re.compile(r"the (optic|olfactory|facial|trigeminal|vagus|phrenic|ulnar|median|radial|femoral|sciatic|tibial|peroneal|sural|saphenous|pudendal) nerve", re.I),
    re.compile(r"the (cerebellum|cerebrum|medulla|pons|thalamus|amygdala|hippocampus|prefrontal|motor cortex|sensory cortex|visual cortex|auditory cortex)", re.I),
]


def curate_true_or_lie(statements: list[dict]) -> list[dict]:
    out: list[dict] = []
    seen: set[str] = set()
    for s in statements:
        text = s.get("text", "").strip()
        key = text.lower()
        if not text or key in seen:
            continue
        if any(p.search(text) for p in DROP_TRUE_OR_LIE_PATTERNS):
            continue
        # Prefer tricky items; allow surprising truths and classic myths
        is_tricky = any(p.search(text) for p in KEEP_TRUE_OR_LIE_PATTERNS)
        is_short_myth = len(text) < 120 and ("." in text)
        if is_tricky or is_short_myth:
            seen.add(key)
            out.append({"text": text, "isTrue": bool(s.get("isTrue"))})
    return out[:300]


def write_json(path: Path, data: object) -> None:
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"Wrote {path.relative_to(ROOT)}")


def main() -> None:
    print("=== Applying LLM hand curation ===")

    # Preserve curated MC trivia (API content is fine)
    mc_path = ROOT / "content/trivia/multiple-choice.json"
    mc = json.loads(mc_path.read_text(encoding="utf-8"))
    mc["questions"] = dedupe_mc(mc.get("questions", []))[:2000]
    write_json(mc_path, mc)

    tol_path = ROOT / "content/trivia/true-or-lie.json"
    tol_raw = json.loads(tol_path.read_text(encoding="utf-8")).get("statements", [])
    tol = curate_true_or_lie(tol_raw)
    if len(tol) < 200:
        tol = dedupe_statements(tol_raw)[:300]
    write_json(tol_path, {"statements": tol})

    draw = dedupe_strings(DRAW_GUESS)[:350]
    shirts = dedupe_strings(SHIRT_DESIGNS)[:120]
    write_json(ROOT / "content/drawing/prompts.json", {"drawGuess": draw, "shirtDesigns": shirts})

    wv = {
        "quiplash": dedupe_strings(QUIPLASH)[:500],
        "fibbage": dedupe_fibbage(FIBBAGE)[:200],
        "finishSentence": dedupe_strings(FINISH_SENTENCE)[:50],
        "pitch": dedupe_strings(PITCH)[:40],
        "textTransform": dedupe_strings(TEXT_TRANSFORM)[:40],
        "wordChain": dedupe_strings(WORD_CHAIN, min_len=4)[:80],
        "debate": dedupe_strings(DEBATE)[:80],
        "rank": dedupe_strings(RANK)[:60],
        "sort": dedupe_strings(SORT)[:60],
        "bracket": dedupe_strings(BRACKET)[:40],
        "roleLabel": dedupe_strings(ROLE_LABEL)[:40],
        "teamwork": dedupe_strings(TEAMWORK)[:50],
        "hiddenTask": dedupe_strings(HIDDEN_TASK)[:50],
    }
    write_json(ROOT / "content/write-vote/prompts.json", wv)

    print("\n=== Curated counts ===")
    print(f"  multiple-choice: {len(mc['questions'])}")
    print(f"  true-or-lie:     {len(tol)}")
    print(f"  drawGuess:       {len(draw)}")
    print(f"  shirtDesigns:    {len(shirts)}")
    for k, v in wv.items():
        print(f"  {k}: {len(v)}")
    print("Curation complete.")


if __name__ == "__main__":
    main()