"""Hand-curated Jackbox-style party prompts — LLM-reviewed for a fun 20s friend group."""

from __future__ import annotations

# --- QUIPLASH (500) ---

QUIPLASH: list[str] = [
    "A terrible name for a strip club next to a church",
    "The worst thing to yell during a eulogy",
    "A rejected Tinder bio line",
    "What your therapist secretly labels you as",
    "A bad name for a vegan strip club",
    "The worst thing to say after one night stand",
    "A new flavor of La Croix nobody asked for",
    "The title of your sex tape",
    "A terrible name for a couples therapy retreat",
    "What the devil would put on his Hinge profile",
    "A rejected name for a frat house",
    "The worst superhero name for a guy with IBS",
    "Something you should never say to a cop while drunk",
    "A bad name for a funeral home DJ service",
    "The worst thing to whisper during a prostate exam",
    "A rejected Olympic event for hungover people",
    "What aliens think humans do on Saturday nights",
    "A terrible name for a baby shower stripper",
    "The worst pickup line at a family reunion",
    "A slogan for a haunted OnlyFans",
    "The worst thing to tattoo above your butt",
    "A rejected name for a rage room for couples",
    "What your group chat would be called as a band",
    "A bad name for a podcast about your exes",
    "The worst thing to bring on a first date",
    "A rejected theme for a bachelor party",
    "What you'd name a drink after your worst ex",
    "A terrible name for a gym that only serves beer",
    "The worst thing to say when caught sexting",
    "A rejected kids' show about divorce",
    "What your Roman Empire actually is",
    "A bad name for a church that serves mimosas",
    "The worst thing to yell at a gender reveal",
    "A rejected name for a startup that sells nothing",
    "What you'd call a cult for people who hate plans",
    "A terrible name for a restaurant that only serves gas station food",
    "The worst thing to say during a job interview at a brewery",
    "A rejected Hallmark card for your situationship",
    "What your drunk alter ego is named",
    "A bad name for a yoga class that serves shots",
    "The worst thing to name your Wi-Fi network",
    "A rejected name for a dating app for people who ghost",
    "What you'd title your autobiography if you had no shame",
    "A terrible name for a haunted Hooters",
    "The worst thing to say when your card declines",
    "A rejected name for a support group for people who overshare",
    "What aliens think dating apps are for",
    "A bad name for a coffee shop that only sells Red Bull",
    "The worst thing to yell during a yoga class",
    "A rejected name for a theme park based on your group chat",
    "What you'd name a perfume that smells like regret",
    "A terrible name for a pet snake owned by a frat guy",
    "The worst thing to say at your ex's wedding",
    "A rejected name for a reality show about your friend group",
    "What your browser history would be called as a movie",
    "A bad name for a bar called 'We Have a Bathroom'",
    "The worst thing to say when meeting your partner's parents drunk",
    "A rejected name for a gym where nobody works out",
    "What you'd call a religion based on brunch",
    "A terrible name for a haunted Airbnb in Vegas",
    "The worst thing to text at 2am",
    "A rejected name for a crypto coin backed by vibes",
    "What your most toxic trait would be as a Pokémon",
    "A bad name for a clinic that treats hangovers and bad decisions",
    "The worst thing to say during a breakup in a Uber",
    "A rejected name for a cooking show for people who only order delivery",
    "What you'd name a theme park ride based on your last situationship",
    "A terrible name for a support group for people who can't shut up",
    "The worst thing to yell during a silent retreat",
    "A rejected name for a book club that only reads texts",
    "What your group chat's villain origin story is called",
    "A bad name for a wedding venue inside a Dave & Buster's",
    "The worst thing to say when someone says 'we need to talk'",
    "A rejected name for a meditation app for people who hate peace",
    "What you'd call a cologne called 'Desperation'",
    "A terrible name for a pet hamster in a frat house",
    "The worst thing to say during a toast at your boss's party",
    "A rejected name for a travel show for people who never leave the couch",
    "What aliens think 'rizz' means",
    "A bad name for a hair salon called 'It'll Grow Back'",
    "The worst thing to say when caught looking at your ex's Instagram",
    "A rejected name for a gym that judges you out loud",
    "What you'd name a candle that smells like a frat house",
    "A terrible name for a daycare run by college seniors",
    "The worst thing to yell during a pregnancy announcement",
    "A rejected name for a dating show where everyone is already talking to your ex",
    "What your drunk food order says about you",
    "A bad name for a liquor store called 'Bad Decisions'",
    "The worst thing to say when the waiter says 'enjoy your meal'",
    "A rejected name for a podcast hosted by your intrusive thoughts",
    "What you'd call a support group for people who reply-all",
    "A terrible name for a haunted Tinder date",
    "The worst thing to say when your mom finds your search history",
    "A rejected name for a restaurant where the chef is your ex",
    "What your sleep paralysis demon would put on LinkedIn",
    "A bad name for a bar where every drink is named after an ex",
    "The worst thing to say during a Zoom job interview shirtless",
    "A rejected name for a theme park based on your worst hangover",
    "What you'd name a cologne for people who don't shower",
    "A terrible name for a pet goldfish named Debt",
    "The worst thing to yell during a library",
    "A rejected name for a cooking class that only teaches ramen",
    "What aliens think humans mean by 'it's complicated'",
    "A bad name for a yoga studio that plays drill music",
    "The worst thing to say when someone shows you their baby",
    "A rejected name for a reality show called 'Who Texted Who'",
    "What you'd title a documentary about your friend group's group chat",
    "A terrible name for a strip mall psychic",
    "The worst thing to say when your card works after it declined",
    "A rejected name for a gym for people who only do arm day",
    "What your Uber driver thinks your story is",
    "A bad name for a wedding planner for people who met last month",
    "The worst thing to yell during a christening",
    "A rejected name for a bar called 'Nobody Knows Your Name'",
    "What you'd call a dating app where everyone has seen you cry",
    "A terrible name for a haunted frat house",
    "The worst thing to say when caught in a lie by your mom",
    "A rejected name for a podcast about people who peaked in high school",
    "What aliens think 'no cap' means",
    "A bad name for a restaurant where the menu is just chicken nuggets",
    "The worst thing to say during a performance review",
    "A rejected name for a support group for chronic oversharers on Instagram",
    "What you'd name a beer called 'Questionable Choices'",
    "A terrible name for a pet snake named Venmo Request",
    "The worst thing to yell during a marathon proposal",
    "A rejected name for a theme park ride called 'Emotional Damage'",
    "What your drunk texts would be called as a poetry book",
    "A bad name for a clinic treating both STDs and ego",
    "The worst thing to say when someone says 'I love you' too soon",
    "A rejected name for a cooking show where everything is air-fried",
    "What aliens think humans do with phones in bathrooms",
    "A terrible name for a haunted dorm shower",
    "The worst thing to say at a funeral open mic",
    "A rejected name for a dating app for people who love drama",
    "What you'd call a cologne named 'Last Night'",
    "A bad name for a gym where the weights judge you",
    "The worst thing to yell during a meditation app ad",
    "A rejected name for a podcast called 'That's What She Said'",
    "What your situationship would be called as a horror movie",
    "A terrible name for a pet dog named Sublet",
    "The worst thing to say when your ex walks into the bar",
    "A rejected name for a restaurant that only serves breakup food",
    "What aliens think 'ghosting' literally means",
    "A bad name for a bar called 'We Don't Card Hard'",
    "The worst thing to say during a couples massage",
    "A rejected name for a reality show about your roster",
    "What you'd title your LinkedIn if honesty was allowed",
    "A terrible name for a haunted spring break Airbnb",
    "The worst thing to yell during a baby gender reveal fire",
    "A rejected name for a support group for people who can't cook",
    "What your group chat would be called as a horror franchise",
    "A bad name for a wedding DJ who only plays breakup songs",
    "The worst thing to say when the bill arrives on a first date",
    "A rejected name for a theme park based on your bank account",
    "What you'd name a drink called 'Walk of Shame'",
    "A terrible name for a pet cat named Red Flag",
    "The worst thing to say during a sobriety checkpoint",
    "A rejected name for a podcast about your worst dates",
    "What aliens think 'slay' means at a funeral",
    "A bad name for a coffee shop called 'Anxiety on Ice'",
    "The worst thing to yell during a vow renewal",
    "A rejected name for a dating app where your ex is always online",
    "What your browser incognito tab would be called as a show",
    "A terrible name for a haunted Vegas chapel",
    "The worst thing to say when caught stalking on social media",
    "A rejected name for a gym called 'New Year, Same You'",
    "What you'd call a candle that smells like a dive bar",
    "A bad name for a pet fish named Situationship",
    "The worst thing to say during a police traffic stop",
    "A rejected name for a cooking show for people who microwave everything",
    "What aliens think humans mean by 'I'm fine'",
    "A terrible name for a strip club called 'Closed for Feelings'",
    "The worst thing to yell during a TED talk",
    "A rejected name for a bar where every stool has a story",
    "What your drunk Amazon orders would be called as a museum",
    "A bad name for a wedding venue in a Taco Bell",
    "The worst thing to say when your card declines on a date",
    "A rejected name for a podcast hosted by your hangxiety",
    "What you'd name a theme park ride based on your last text",
    "A terrible name for a haunted fraternity basement",
    "The worst thing to say during a family dinner after college",
    "A rejected name for a dating app for people who love red flags",
    "What aliens think 'main character energy' is",
    "A bad name for a restaurant where every dish is beige",
    "The worst thing to yell during a yoga retreat",
    "A rejected name for a support group for people who can't stop quoting memes",
    "What you'd call a perfume named 'Regret'",
    "A terrible name for a pet hamster named Overdraft",
    "The worst thing to say when someone catches you lying",
    "A rejected name for a reality show about your roster drama",
    "What your group chat arguments would be called as a courtroom show",
    "A bad name for a bar called 'Free Wi-Fi, Expensive Mistakes'",
    "The worst thing to say during a breakup in a shared Uber",
    "A rejected name for a theme park called 'Debt Mountain'",
    "What aliens think 'rizz' is medically",
    "A terrible name for a haunted college laundry room",
    "The worst thing to yell during a silent auction",
    "A rejected name for a podcast about people who never text back",
    "What you'd title a memoir called 'It Seemed Like a Good Idea'",
    "A bad name for a gym where everyone skips leg day forever",
    "The worst thing to say when your mom joins your Zoom call",
    "A rejected name for a dating show where everyone dated everyone",
    "What your sleep schedule would be called as a horror film",
    "A terrible name for a pet snake named Crypto Loss",
    "The worst thing to say during a toast at a divorce party",
    "A rejected name for a restaurant that only serves gas station sushi",
    "What aliens think humans do at 3am",
    "A bad name for a wedding planner for Vegas mistakes",
    "The worst thing to yell during a company all-hands",
    "A rejected name for a bar called 'We Have a Patio'",
    "What you'd name a drink called 'Bad Decisions'",
    "A terrible name for a haunted dating app headquarters",
    "The worst thing to say when caught screenshotting",
    "A rejected name for a support group for chronic snooze button users",
    "What your roster would be called as a fantasy sports league",
    "A bad name for a coffee shop called 'No Sleep Only Vibes'",
    "The worst thing to say during a proposal gone wrong",
    "A rejected name for a theme park based on your texts",
    "What aliens think 'delulu' means",
    "A terrible name for a pet dog named Ghosted",
    "The worst thing to yell during a baptism",
    "A rejected name for a podcast called 'Red Flag Parade'",
    "What your drunk voice notes would be called as an album",
    "A bad name for a clinic for hangovers and heartbreak",
    "The worst thing to say when your ex likes your photo",
    "A rejected name for a cooking show where everything is drunk food",
    "What you'd call a cologne named 'Desperation and Axe'",
    "A terrible name for a haunted spring break hotel",
    "The worst thing to say during a job interview hungover",
    "A rejected name for a dating app where everyone knows your business",
    "What aliens think 'soft launch' means in warfare",
    "A bad name for a restaurant called 'We Have a Bathroom Key'",
    "The worst thing to yell during a mindfulness class",
    "A rejected name for a reality show about your situationships",
    "What your bank account would say if it could talk",
    "A terrible name for a pet goldfish named Rent Due",
    "The worst thing to say when caught in your ex's neighborhood",
    "A rejected name for a bar where every drink is a mistake",
    "What you'd title a show about your friend group's chaos",
    "A bad name for a wedding DJ who only plays Drake",
    "The worst thing to say during a sobriety toast",
    "A rejected name for a theme park ride called 'Credit Score Drop'",
    "What aliens think 'ick' is as a disease",
    "A terrible name for a haunted frat formal",
    "The worst thing to yell during a baby shower",
    "A rejected name for a podcast about your worst hangovers",
    "What your DoorDash history reveals about you",
    "A bad name for a gym called 'New Year New Me (Same Me)'",
    "The worst thing to say when someone says they're pregnant",
    "A rejected name for a dating app for people who love chaos",
    "What you'd name a beer called 'One More'",
    "A terrible name for a pet cat named Walk of Shame",
    "The worst thing to say during a performance review after a bender",
    "A rejected name for a cooking class that only teaches cereal",
    "What aliens think humans mean by 'we should hang out soon'",
    "A bad name for a strip club called 'Closed for Therapy'",
    "The worst thing to yell during a graduation speech",
    "A rejected name for a support group for people who can't stop scrolling",
    "What your situationship would be called as a weather report",
    "A terrible name for a haunted college advisor office",
    "The worst thing to say when your card declines at brunch",
    "A rejected name for a theme park based on your roster",
    "What you'd call a candle that smells like a frat formal",
    "A bad name for a wedding venue inside a Waffle House",
    "The worst thing to say during a couples therapy icebreaker",
    "A rejected name for a podcast called 'That's a Red Flag'",
    "What your group chat would be called as a true crime show",
    "A terrible name for a pet hamster named Situationship Jr",
    "The worst thing to yell during a vow of silence",
    "A rejected name for a bar called 'Happy Hour All Day'",
    "What aliens think 'ghosting' is as a sport",
    "A bad name for a restaurant where the chef is everyone's ex",
    "The worst thing to say when caught lying to your roommate",
    "A rejected name for a dating show called 'Exes & Ohs'",
    "What you'd title a book about your worst spring break",
    "A terrible name for a haunted Vegas wedding chapel",
    "The worst thing to say during a family game night",
    "A rejected name for a theme park ride called 'Hangxiety Hill'",
    "What your drunk texts would be called as Shakespeare",
    "A bad name for a coffee shop called 'Anxiety Latte'",
    "The worst thing to yell during a funeral selfie",
    "A rejected name for a podcast about people who peaked in college",
    "What aliens think 'no thoughts head empty' means medically",
    "A terrible name for a pet snake named Overthinker",
    "The worst thing to say when your ex is the bartender",
    "A rejected name for a gym where everyone films themselves",
    "What you'd name a cologne called 'Last Call'",
    "A bad name for a wedding planner for shotgun weddings",
    "The worst thing to say during a Zoom date",
    "A rejected name for a reality show about your group trip",
    "What your browser history would be called as a horror podcast",
    "A terrible name for a haunted dorm move-in day",
    "The worst thing to yell during a mindfulness retreat",
    "A rejected name for a bar called 'We Card Sometimes'",
    "What aliens think 'rizz' is in chemistry class",
    "A bad name for a restaurant that only serves drunk food",
    "The worst thing to say when someone says 'define the relationship'",
    "A rejected name for a dating app where your mom is also on it",
    "What you'd call a support group for chronic overthinkers",
    "A terrible name for a pet dog named Red Flag II",
    "The worst thing to say during a toast at a rehearsal dinner",
    "A rejected name for a theme park called 'Emotional Whiplash'",
    "What your sleep paralysis demon would name its podcast",
    "A bad name for a clinic treating both hangovers and heartbreak",
    "The worst thing to yell during a silent disco",
    "A rejected name for a podcast called 'Group Chat Court'",
    "What aliens think humans do with AirPods in",
    "A terrible name for a haunted college registration line",
    "The worst thing to say when caught in a lie on a date",
    "A rejected name for a cooking show for people who only eat nuggets",
    "What you'd title your autobiography: __________",
    "A bad name for a bar called 'Free Shots, Expensive Therapy'",
    "The worst thing to say during a breakup at a wedding",
    "A rejected name for a dating app for people who love situationships",
    "What your roster would be called as a Marvel team",
    "A terrible name for a pet goldfish named Ghosted Too",
    "The worst thing to yell during a company retreat trust fall",
    "A rejected name for a theme park based on your bank statements",
    "What aliens think 'delulu is the solulu' means",
    "A bad name for a wedding DJ who only plays breakup bangers",
    "The worst thing to say when your mom finds your finsta",
    "A rejected name for a support group for people who can't cook ramen right",
    "What you'd name a drink called 'Questionable Life Choices'",
    "A terrible name for a haunted Vegas pool party",
    "The worst thing to say during a job interview after a rave",
    "A rejected name for a podcast about your worst Uber rides",
    "What your group chat would be called as a soap opera",
    "A bad name for a gym called 'Gains and Regrets'",
    "The worst thing to yell during a gender reveal explosion",
    "A rejected name for a bar where every night is karaoke night",
    "What aliens think 'soft boy' means in the military",
    "A terrible name for a pet hamster named Credit Score",
    "The worst thing to say when someone says 'I'm not like other guys'",
    "A rejected name for a dating show where everyone shares an ex",
    "What your drunk Amazon cart would be called as art",
    "A bad name for a restaurant called 'We Don't Judge (We Judge)'",
    "The worst thing to say during a sobriety pledge",
    "A rejected name for a theme park ride called 'Text Back Terror'",
    "What you'd call a perfume named '2am Decisions'",
    "A terrible name for a haunted college dining hall",
    "The worst thing to yell during a yoga class hungover",
    "A rejected name for a podcast called 'That's What He Said'",
    "What aliens think 'main character' means in a hospital",
    "A bad name for a wedding venue in a gas station parking lot",
    "The worst thing to say when your card declines at the club",
    "A rejected name for a support group for chronic meme reposters",
    "What your situationship would be called as a weather alert",
    "A terrible name for a pet cat named Venmo Me",
    "The worst thing to say during a family photo",
    "A rejected name for a cooking show where everything is deep-fried",
    "What you'd title a documentary about your worst decisions",
    "A bad name for a bar called 'Last Call Forever'",
    "The worst thing to yell during a christening afterparty",
    "A rejected name for a dating app where everyone has your number",
    "What aliens think humans mean by 'I'm not drunk'",
    "A terrible name for a haunted spring break cruise",
    "The worst thing to say when caught stalking your ex's new partner",
    "A rejected name for a theme park called 'Roster Rotation'",
    "What your drunk voice memo would be called as a TED talk",
    "A bad name for a clinic for STDs and situationships",
    "The worst thing to say during a toast at your own wedding",
    "A rejected name for a podcast about people who never grew up",
    "What you'd name a beer called 'One More (Famous Last Words)'",
    "A terrible name for a pet snake named Group Chat Drama",
    "The worst thing to yell during a library rave",
    "A rejected name for a bar called 'We Have a Parking Lot'",
    "What aliens think 'ick' is on a medical chart",
    "A bad name for a restaurant where every meal is shared with your ex",
    "The worst thing to say when your roommate walks in",
    "A rejected name for a dating show called 'Love Island But Everyone Knows You'",
    "What your group chat would be called as a wrestling promotion",
    "A terrible name for a haunted college career fair",
    "The worst thing to say during a performance review after spring break",
    "A rejected name for a theme park ride called 'Hangover Mountain'",
    "What you'd call a cologne named 'Bad Idea'",
    "A bad name for a wedding planner for people who met at 2am",
    "The worst thing to yell during a silent meditation retreat",
    "A rejected name for a podcast called 'Red Flag Radio'",
    "What aliens think humans do with dating app notifications",
    "A terrible name for a pet dog named Situationship 2: Electric Boogaloo",
    "The worst thing to say when someone says 'we need a break'",
    "A rejected name for a gym called 'Leg Day Never'",
    "What your browser incognito history would be called as a novel",
    "A bad name for a coffee shop called 'No Sleep Club'",
    "The worst thing to say during a breakup on Valentine's Day",
    "A rejected name for a reality show about your friend group's roster",
    "What you'd title a memoir called 'I Thought It Would Be Different'",
    "A terrible name for a haunted Vegas bachelor party suite",
    "The worst thing to yell during a baby naming ceremony",
    "A rejected name for a bar called 'Happy Hour Unhappy People'",
    "What aliens think 'ghosting' is in paranormal studies",
    "A bad name for a restaurant that only serves food from your ex's culture",
    "The worst thing to say when caught lying to your best friend",
    "A rejected name for a dating app for people who love toxic traits",
    "What your roster would be called as a fantasy football team",
    "A terrible name for a pet goldfish named Rent and Ruin",
    "The worst thing to say during a Zoom funeral",
    "A rejected name for a theme park based on your worst hangover stories",
    "What you'd name a drink called 'Walk of Fame (Shame)'",
    "A bad name for a wedding DJ who only plays your ex's songs",
    "The worst thing to yell during a company holiday party",
    "A rejected name for a podcast about your worst decisions",
    "What aliens think 'no cap' is in fashion",
    "A terrible name for a haunted college finals week",
    "The worst thing to say when your ex is your Uber driver",
    "A rejected name for a support group for people who can't stop drunk texting",
    "What your group chat would be called as a reality competition",
    "A bad name for a gym called 'New Year Same Hangover'",
    "The worst thing to say during a proposal at a game",
    "A rejected name for a bar called 'We Have a Dance Floor (Barely)'",
    "What you'd call a candle that smells like regret and Axe body spray",
    "A terrible name for a pet hamster named Overdraft Fee",
    "The worst thing to yell during a vow renewal at Denny's",
    "A rejected name for a dating show where your mom picks your dates",
    "What aliens think humans mean by 'it's not serious'",
    "A bad name for a restaurant called 'We Have a Happy Hour (Sad Hour)'",
    "The worst thing to say when someone catches you screenshotting their story",
    "A rejected name for a theme park ride called 'Credit Card Declined'",
    "What your drunk texts would be called as ancient prophecy",
    "A terrible name for a haunted fraternity pledge night",
    "The worst thing to say during a family reunion after college",
    "A rejected name for a podcast called 'That's a You Problem'",
    "What you'd title a show about your worst spring break decisions",
    "A bad name for a clinic treating hangovers and hubris",
    "The worst thing to yell during a silent yoga class",
    "A rejected name for a dating app where everyone dated your roommate",
    "What aliens think 'rizz' is in a lab report",
    "A terrible name for a pet snake named Bad Decision",
    "The worst thing to say when your card declines buying drinks for the table",
    "A rejected name for a cooking show for people who only eat cereal at 3am",
    "What your situationship would be called as a stock ticker",
    "A bad name for a wedding venue inside a Dave & Buster's after midnight",
    "The worst thing to say during a toast at a divorce reception",
    "A rejected name for a theme park called 'Emotional Damage World'",
    "What aliens think humans do with 'do not disturb' mode",
    "A terrible name for a haunted college laundry at 2am",
    "The worst thing to yell during a mindfulness app notification",
    "A rejected name for a bar called 'Free Regrets'",
    "What you'd name a cologne called 'Mistake'",
    "A bad name for a support group for people who can't stop quoting The Office",
    "The worst thing to say when your mom finds your dating apps",
    "A rejected name for a reality show about your roster rotation",
    "What your group chat arguments would be called as WWE storylines",
    "A terrible name for a pet cat named Ghosted Again",
    "The worst thing to say during a job interview at your ex's company",
    "A rejected name for a podcast about people who never apologize",
    "What aliens think 'delulu' is in psychology",
    "A bad name for a restaurant where the chef is your situationship",
    "The worst thing to yell during a gender reveal plane crash",
    "A rejected name for a dating app for people who love being messy",
    "What you'd title your autobiography if your mom wrote it",
    "A terrible name for a haunted Vegas afterparty",
    "The worst thing to say when caught in your ex's DMs",
    "A rejected name for a theme park ride called 'Roster Roulette'",
    "What your drunk DoorDash order says about your mental state",
    "A bad name for a gym called 'Gains? Questionable'",
    "The worst thing to say during a couples game night with your ex",
    "A rejected name for a bar called 'We Have a Roof (Sometimes)'",
    "What aliens think 'main character energy' is in a hospital drama",
    "A terrible name for a pet dog named Red Flag Season 2",
    "The worst thing to yell during a silent retreat talent show",
    "A rejected name for a podcast called 'Group Chat Therapy'",
    "What you'd call a beer named 'Hold My Beer'",
    "A bad name for a wedding planner for people who met on a dare",
    "The worst thing to say when someone says 'I'm pregnant' on a first date",
    "A rejected name for a cooking class that only teaches drunk food",
    "What your browser history would be called as a true crime podcast",
    "A terrible name for a haunted college move-out day",
    "The worst thing to say during a breakup in a shared apartment",
    "A rejected name for a dating show called 'Exes, Texts, and Videotape'",
    "What aliens think humans mean by 'we're just talking'",
    "A bad name for a coffee shop called 'Anxiety and Espresso'",
    "The worst thing to yell during a funeral karaoke",
    "A rejected name for a theme park based on your worst texts",
    "What you'd name a perfume called '2am and Regret'",
    "A terrible name for a pet goldfish named Situationship III",
    "The worst thing to say when your roommate brings home a date",
    "A rejected name for a support group for chronic snooze and lose users",
    "What your roster would be called as a horror anthology",
    "A bad name for a wedding DJ who only plays sad boy hours",
    "The worst thing to say during a sobriety check at brunch",
    "A rejected name for a podcast about your worst college stories",
    "What aliens think 'ick' is in food safety",
    "A terrible name for a haunted spring break Airbnb with 12 guys",
    "The worst thing to yell during a company trust exercise",
    "A rejected name for a bar called 'We Have a Bathroom (Maybe)'",
    "What you'd title a memoir called 'It Made Sense at the Time'",
    "A bad name for a restaurant that only serves food from gas stations",
    "The worst thing to say when caught lying in your group chat",
    "A rejected name for a dating app where everyone is your coworker",
    "What your sleep paralysis demon would post on Instagram",
    "A terrible name for a pet hamster named Bad Idea Jr",
    "The worst thing to say during a toast at a shotgun wedding",
    "A rejected name for a theme park ride called 'Hangxiety Express'",
    "What aliens think 'no thoughts head empty' is as a diagnosis",
    "A bad name for a clinic for heartbreak and hot wings",
    "The worst thing to yell during a baptism afterparty",
    "A rejected name for a reality show about your friend group's chaos",
    "What you'd call a cologne named 'Last Night Was a Mistake'",
    "A terrible name for a haunted college registration website",
    "The worst thing to say when your ex joins your fantasy league",
    "A rejected name for a podcast called 'Red Flag Weekly'",
    "What your drunk voice notes would be called as a horror audiobook",
    "A bad name for a gym called 'New Year, Same Roster'",
    "The worst thing to say during a performance review after Vegas",
    "A rejected name for a bar where every drink is named after a red flag",
    "What aliens think humans do with 'read receipts' off",
    "A terrible name for a pet snake named Group Chat Menace",
    "The worst thing to yell during a silent auction at a frat formal",
    "A rejected name for a dating show where everyone shares a bathroom",
    "What your situationship would be called as a hurricane warning",
    "A bad name for a wedding venue in a Taco Bell parking lot at 3am",
    "The worst thing to say when someone says 'I love you' in a Uber",
    "A rejected name for a theme park called 'Debt and Regret Land'",
    "What you'd name a drink called 'Bad Idea (Large)'",
    "A terrible name for a haunted college advisor Zoom call",
    "The worst thing to say during a family dinner after your roster changed",
    "A rejected name for a cooking show where everything is drunk nachos",
    "What aliens think 'soft launch' means in rocket science",
    "A bad name for a support group for people who can't stop oversharing",
    "The worst thing to yell during a mindfulness class after pregame",
    "A rejected name for a podcast about your worst roster decisions",
    "What your group chat would be called as a disaster movie",
    "A terrible name for a pet cat named Venmo Request Pending",
    "The worst thing to say when caught stalking on LinkedIn",
    "A rejected name for a dating app for people who love chaos and brunch",
    "What you'd title a documentary about your worst Uber pool",
    "A bad name for a bar called 'Free Shots, Pricey Mistakes'",
    "The worst thing to say during a breakup at a friend's wedding",
    "A rejected name for a theme park ride called 'Emotional Rollercoaster (Literally)'",
    "What aliens think 'rizz' is in a physics equation",
    "A terrible name for a haunted Vegas wedding afterparty",
    "The worst thing to yell during a graduation afterparty",
    "A rejected name for a podcast called 'That's a Red Flag (Again)'",
    "What your drunk Amazon history would be called as a museum exhibit",
    "A bad name for a wedding DJ who only plays breakup anthems",
    "The worst thing to say when your mom follows your finsta",
    "A rejected name for a gym called 'Gains and Questionable Decisions'",
    "What aliens think humans mean by 'I'm different when I'm drunk'",
    "A terrible name for a pet goldfish named Roster Spot #4",
    "The worst thing to say during a Zoom date with your camera off",
    "A rejected name for a bar called 'We Have a Patio (Smokers Only)'",
    "What you'd call a candle that smells like a bad decision",
    "A bad name for a restaurant where every table has an ex",
    "The worst thing to yell during a silent retreat group share",
    "A rejected name for a dating show called 'Love on the Roster'",
    "What your browser incognito tab would be called as a thriller",
    "A terrible name for a haunted college dining hall at midnight",
    "The worst thing to say when your card declines on a group tab",
    "A rejected name for a theme park based on your worst 2am texts",
    "What aliens think 'ghosting' is in fishing",
    "A bad name for a clinic treating both ego and UTIs",
    "The worst thing to say during a toast at your ex's engagement party",
    "A rejected name for a podcast about people who peaked in freshman year",
    "What you'd name a beer called 'One More for the Road (Bad Idea)'",
    "A terrible name for a pet hamster named Credit Limit",
    "The worst thing to yell during a library study group that turned into pregame",
    "A rejected name for a support group for chronic drunk Amazon shoppers",
    "What your roster would be called as a March Madness bracket",
    "A bad name for a coffee shop called 'No Sleep, Only Regret'",
    "The worst thing to say when someone says 'we should be exclusive'",
    "A rejected name for a reality show about your spring break roster",
    "What aliens think 'delulu is the solulu' is as a motto",
    "A terrible name for a haunted fraternity basement at 3am",
    "The worst thing to say during a job interview when they ask about gaps in your resume",
    "A rejected name for a bar called 'Happy Hour, Unhappy Life'",
    "What you'd title your autobiography if your group chat wrote it",
    "A bad name for a wedding planner for people who met in a Uber pool",
    "The worst thing to yell during a gender reveal that started a fire",
    "A rejected name for a dating app where your ex is always suggested",
    "What your situationship would be called as a weather warning",
    "A terrible name for a pet snake named Bad Text",
    "The worst thing to say when caught in a lie to your situationship",
    "A rejected name for a theme park ride called 'Roster Wipeout'",
    "What aliens think humans do with 'last seen' timestamps",
    "A bad name for a gym called 'Leg Day is a Myth'",
    "The worst thing to say during a couples therapy homework assignment",
    "A rejected name for a podcast called 'Group Chat Crimes'",
    "What your drunk texts would be called as a Shakespeare tragedy",
    "A terrible name for a haunted college career counseling office",
    "The worst thing to yell during a silent disco at a funeral",
    "A rejected name for a cooking show for people who only eat drunk pizza",
    "What you'd call a perfume named 'Mistake at Midnight'",
    "A bad name for a restaurant called 'We Have a Special (Regret)'",
    "The worst thing to say when your roommate's ex shows up",
    "A rejected name for a dating show where everyone is in your group chat",
    "What your bank account would tweet if it had Twitter",
    "A terrible name for a pet dog named Situationship Final Boss",
    "The worst thing to say during a breakup on New Year's Eve",
    "A rejected name for a theme park called 'Hangover Kingdom'",
    "What aliens think 'ick' is in a lab experiment",
    "A bad name for a wedding venue inside a Waffle House at closing time",
    "The worst thing to yell during a company diversity training",
    "A rejected name for a bar called 'We Have a Pool Table (Broken)'",
    "What you'd name a cologne called 'Questionable Choices'",
    "A terrible name for a haunted Vegas pool after dark",
    "The worst thing to say when your ex is the wedding photographer",
    "A rejected name for a podcast about your worst roster trades",
    "What aliens think 'main character' means in a psych evaluation",
    "A bad name for a support group for people who can't stop sending memes",
    "The worst thing to say during a family photo after a bender",
    "A rejected name for a dating app for people who love being the problem",
    "What your group chat would be called as an HBO drama",
    "A terrible name for a pet goldfish named Rent Is Due",
    "The worst thing to yell during a vow of silence at a wedding",
    "A rejected name for a theme park ride called 'Text Back or Die'",
    "What your drunk DoorDash driver thinks your life is like",
    "A bad name for a clinic for heartbreak and heartburn",
    "The worst thing to say when someone says 'I'm not ready for a relationship'",
    "A rejected name for a cooking class that only teaches gas station food",
    "What aliens think humans mean by 'it's casual'",
    "A terrible name for a haunted spring break house with one bathroom",
    "The worst thing to say during a toast at a breakup party",
    "A rejected name for a podcast called 'Red Flag Reunion'",
    "What you'd title a show about your worst college roster",
    "A bad name for a gym called 'New Year, Same Mistakes'",
    "The worst thing to yell during a mindfulness retreat hungover",
    "A rejected name for a bar called 'Free Entry, Expensive Dignity'",
    "What aliens think 'no cap' is in a chemistry lab",
    "A terrible name for a pet hamster named Overdraft King",
    "The worst thing to say when caught screenshotting a private story",
    "A rejected name for a dating show called 'Exes in the Building'",
    "What your browser history would be called as a Netflix true crime series",
    "A bad name for a wedding DJ who only plays your situationship songs",
    "The worst thing to say during a performance review after a roster change",
    "A rejected name for a theme park based on your worst decisions",
    "What you'd call a beer named 'Hold My Beer (Famous Last Words)'",
    "A terrible name for a haunted college registration day",
    "The worst thing to yell during a silent auction at a divorce party",
    "A rejected name for a podcast about people who never learn",
    "What aliens think 'rizz' is in a biology textbook",
    "A bad name for a restaurant where every dish reminds you of an ex",
    "The worst thing to say when your mom asks who you're texting",
    "A rejected name for a support group for chronic roster managers",
    "What your situationship would be called as a tornado siren",
    "A terrible name for a pet cat named Ghosted Final Season",
    "The worst thing to say during a Zoom call with your boss and your ex",
    "A rejected name for a dating app where everyone knows your roster",
    "What you'd name a drink called 'Walk of Shame (Extra Large)'",
    "A bad name for a coffee shop called 'Anxiety on Tap'",
    "The worst thing to yell during a christening open bar",
    "A rejected name for a theme park ride called 'Credit Score Freefall'",
    "What aliens think humans do with 'typing...' for 20 minutes",
    "A terrible name for a haunted fraternity formal bathroom",
    "The worst thing to say when your card declines at the worst possible moment",
    "A rejected name for a bar called 'We Have a Karaoke Night (Regret Night)'",
    "What your group chat would be called as a courtroom drama",
    "A bad name for a wedding planner for Vegas mistakes at 4am",
    "The worst thing to say during a breakup in a group Uber",
    "A rejected name for a podcast called 'That's What Your Therapist Said'",
    "What aliens think 'delulu' is on a prescription bottle",
    "A terrible name for a pet snake named Roster Drama",
    "The worst thing to yell during a graduation speech drunk",
    "A rejected name for a cooking show where everything is gas station sushi",
    "What you'd title a memoir called 'I Swear I Learned My Lesson'",
    "A bad name for a gym called 'Gains? Debatable.'",
    "The worst thing to say when someone says 'my ex wasn't that bad'",
    "A rejected name for a dating show where your mom is a contestant",
    "What your drunk voice notes would be called as a comedy special",
    "A terrible name for a haunted college laundry during finals",
    "The worst thing to say during a toast at your own engagement party (wrong person)",
    "A rejected name for a theme park called 'Emotional Whiplash World'",
    "What aliens think 'soft boy' means in boot camp",
    "A bad name for a clinic treating hangovers and heartbreak since 2019",
    "The worst thing to yell during a silent yoga class after tailgate",
    "A rejected name for a podcast about your worst spring break roster",
    "What your roster would be called as a fantasy draft gone wrong",
    "A terrible name for a pet goldfish named Situationship: The Finale",
    "The worst thing to say when caught in your ex's building",
    "A rejected name for a bar called 'Last Call (First Mistake)'",
    "What aliens think 'ghosting' is in a horror movie",
    "A bad name for a restaurant called 'We Have a Bathroom Key (Maybe Not)'",
    "The worst thing to say during a family game night after pregame",
    "A rejected name for a dating app for people who love roster chaos",
    "What you'd call a candle that smells like a frat house at 3am",
    "A terrible name for a haunted Vegas wedding suite",
    "The worst thing to yell during a baby shower open bar",
    "A rejected name for a theme park ride called 'Hangxiety Drop Tower'",
    "What your browser incognito history would be called as a documentary",
    "A bad name for a wedding DJ who only plays Drake at funerals",
    "The worst thing to say when your roommate walks in during a FaceTime date",
    "A rejected name for a podcast called 'Group Chat Witness Protection'",
    "What aliens think humans mean by 'I'm never drinking again'",
    "A terrible name for a pet hamster named Bad Decision 3",
    "The worst thing to say during a job interview when they ask about your finsta",
    "A rejected name for a support group for people who can't stop roster shuffling",
    "What you'd name a cologne called '2am and Poor Choices'",
    "A bad name for a coffee shop called 'No Sleep, Only Chaos'",
    "The worst thing to yell during a funeral open mic night",
    "A rejected name for a reality show about your friend group's spring break",
    "What your situationship would be called as a tsunami alert",
    "A terrible name for a haunted college dining hall during rush",
    "The worst thing to say when someone says 'we're just hanging out'",
    "A rejected name for a bar called 'Happy Hour All Night (Sad Morning)'",
    "What aliens think 'ick' is in a food recall",
    "A bad name for a gym called 'New Year New Me (Narrator: He Did Not)'",
    "The worst thing to say during a breakup at a destination wedding",
    "A rejected name for a dating show called 'Love Island: Roster Edition'",
    "What your group chat would be called as a survival show",
    "A terrible name for a pet dog named Red Flag: The Trilogy",
    "The worst thing to yell during a company holiday party open bar",
    "A rejected name for a theme park based on your worst roster week",
    "What you'd title a book about your worst drunk texts",
    "A bad name for a wedding venue in a gas station at midnight",
    "The worst thing to say when your ex is your new coworker",
    "A rejected name for a podcast about people who never change",
    "What aliens think 'no thoughts head empty' is as a meditation goal",
    "A terrible name for a haunted spring break cruise bathroom",
    "The worst thing to say during a toast at a rehearsal dinner (wrong couple)",
    "A rejected name for a cooking show for people who only eat drunk tacos",
    "What you'd call a beer named 'One More (Narrator: There Was Another)'",
    "A bad name for a clinic for STDs, ego, and situationships",
    "The worst thing to yell during a silent retreat after one beer",
    "A rejected name for a dating app where your roster is public",
    "What your drunk Amazon cart would be called as modern art",
    "A terrible name for a pet snake named Group Chat Final Boss",
    "The worst thing to say when caught lying on your dating profile",
    "A rejected name for a bar called 'We Have a Roof (Leaks)'",
    "What aliens think 'main character energy' is in a group project",
    "A bad name for a support group for chronic 'wyd' texters",
    "The worst thing to say during a performance review after roster drama",
    "A rejected name for a theme park ride called 'Emotional Damage: The Ride'",
    "What your sleep paralysis demon would name its finsta",
    "A terrible name for a haunted college move-in with 8 roommates",
    "The worst thing to yell during a gender reveal at a funeral",
    "A rejected name for a podcast called 'Red Flag Hall of Fame'",
    "What aliens think humans do with 'do not disturb' during situationships",
    "A bad name for a restaurant where the waiter is your ex",
    "The worst thing to say when your mom finds your roster notes",
    "A rejected name for a dating show where everyone dated in the group chat",
    "What you'd name a perfume called 'Mistake o'clock'",
    "A terrible name for a pet goldfish named Rent and Roster",
    "The worst thing to say during a Zoom funeral with open bar at home",
    "A rejected name for a gym called 'Gains and Regrets (Mostly Regrets)'",
    "The worst thing to yell during a mindfulness class during a hangover",
    "A rejected name for a theme park called 'Debt, Regret, and Roster Land'",
    "What your group chat would be called as a limited series",
    "A bad name for a wedding planner for people who met at last call",
    "The worst thing to say when someone says 'I think we should stay friends'",
    "A rejected name for a bar called 'Free Shots, Pricey Therapy'",
    "What aliens think 'delulu is the solulu' is as a life plan",
    "A terrible name for a haunted Vegas after-afterparty",
    "The worst thing to say during a breakup on someone's birthday",
    "A rejected name for a podcast about your worst roster of all time",
    "What you'd title the finale of your situationship season",
]

# --- FIBBAGE (200 hand-picked weird truths) ---

FIBBAGE: list[dict[str, str]] = [
    {"prompt": "The world's largest sauna is located in _____.", "truth": "Finland"},
    {"prompt": "Ancient Romans sometimes paid soldiers in _____.", "truth": "salt"},
    {"prompt": "A group of owls is called a _____.", "truth": "parliament"},
    {"prompt": "The first email ever sent said _____.", "truth": "QWERTYUIOP"},
    {"prompt": "Dolphins sleep with one _____ open.", "truth": "eye"},
    {"prompt": "The shortest war in history lasted _____ minutes.", "truth": "38"},
    {"prompt": "Honey never _____.", "truth": "spoils"},
    {"prompt": "Scotland's national animal is the _____.", "truth": "unicorn"},
    {"prompt": "Wombat poop is _____.", "truth": "cube-shaped"},
    {"prompt": "The inventor of the Pringles can was buried in _____.", "truth": "one"},
    {"prompt": "Cleopatra lived closer to the Moon landing than the Great _____.", "truth": "Pyramid"},
    {"prompt": "Bananas are berries but strawberries are _____.", "truth": "not"},
    {"prompt": "Humans share about 50% of DNA with _____.", "truth": "bananas"},
    {"prompt": "The Anglo-Zanzibar War lasted under _____ minutes.", "truth": "45"},
    {"prompt": "Male seahorses carry the _____.", "truth": "pregnancy"},
    {"prompt": "Ketchup was once sold as _____.", "truth": "medicine"},
    {"prompt": "The Caesar salad was invented in _____.", "truth": "Mexico"},
    {"prompt": "Buffalo wings are named after Buffalo, New _____.", "truth": "York"},
    {"prompt": "Cats cannot taste _____.", "truth": "sweetness"},
    {"prompt": "A snail can sleep for three _____.", "truth": "years"},
    {"prompt": "Horses cannot _____.", "truth": "vomit"},
    {"prompt": "Butterflies taste with their _____.", "truth": "feet"},
    {"prompt": "Crocodiles cannot stick out their _____.", "truth": "tongues"},
    {"prompt": "The mantis shrimp punches with _____-like force.", "truth": "bullet"},
    {"prompt": "Humans are the only animals that _____.", "truth": "blush"},
    {"prompt": "The first computer mouse was made of _____.", "truth": "wood"},
    {"prompt": "The first item sold on eBay was a broken laser _____.", "truth": "pointer"},
    {"prompt": "The first computer bug was a real _____.", "truth": "moth"},
    {"prompt": "A group of flamingos is called a _____.", "truth": "flamboyance"},
    {"prompt": "A group of porcupines is called a _____.", "truth": "prickle"},
    {"prompt": "The Great Emu War was fought in _____.", "truth": "Australia"},
    {"prompt": "Oxford University is older than the _____ Empire.", "truth": "Aztec"},
    {"prompt": "Venus is the hottest _____ in our solar system.", "truth": "planet"},
    {"prompt": "Octopuses have _____ hearts.", "truth": "three"},
    {"prompt": "Sharks are older than _____.", "truth": "trees"},
    {"prompt": "Russia has a larger surface area than _____.", "truth": "Pluto"},
    {"prompt": "The Eiffel Tower grows taller in summer _____.", "truth": "heat"},
    {"prompt": "The word nerd first appeared in a Dr. _____ book.", "truth": "Seuss"},
    {"prompt": "Fortune cookies were popularized in _____, not China.", "truth": "America"},
    {"prompt": "German chocolate cake is named after Sam _____.", "truth": "German"},
    {"prompt": "White chocolate contains no cocoa _____.", "truth": "solids"},
    {"prompt": "Identical twins have different _____.", "truth": "fingerprints"},
    {"prompt": "Koala fingerprints look almost like _____ fingerprints.", "truth": "human"},
    {"prompt": "The Hawaiian pizza was invented in _____.", "truth": "Canada"},
    {"prompt": "Maine is the closest U.S. state to _____.", "truth": "Africa"},
    {"prompt": "Reno, Nevada is farther west than Los _____.", "truth": "Angeles"},
    {"prompt": "Iceland has no _____.", "truth": "mosquitoes"},
    {"prompt": "The War of Jenkins' Ear was a real _____.", "truth": "war"},
    {"prompt": "Napoleon was average height for his _____.", "truth": "era"},
    {"prompt": "Viking battle helmets did not have _____.", "truth": "horns"},
    {"prompt": "Goldfish memory lasts far longer than three _____.", "truth": "seconds"},
    {"prompt": "Bats are not _____.", "truth": "blind"},
    {"prompt": "The far side of the Moon still gets _____.", "truth": "sunlight"},
    {"prompt": "Polaris is not the brightest star; _____ is brighter.", "truth": "Sirius"},
    {"prompt": "A day on Venus is longer than a year on _____.", "truth": "Venus"},
    {"prompt": "The pistol shrimp's bubble is briefly hotter than the _____.", "truth": "sun"},
    {"prompt": "Sea otters hold hands so they don't _____.", "truth": "drift"},
    {"prompt": "Lobsters were once considered poor people's _____.", "truth": "food"},
    {"prompt": "The sandwich is named after the Earl of _____.", "truth": "Sandwich"},
    {"prompt": "Champagne must come from the Champagne region of _____.", "truth": "France"},
    {"prompt": "The QWERTY keyboard was designed to slow _____ down.", "truth": "typists"},
    {"prompt": "The @ symbol was used in commerce before _____ existed.", "truth": "email"},
    {"prompt": "The hashtag symbol is technically called an _____.", "truth": "octothorpe"},
    {"prompt": "French was England's official language for about 300 _____.", "truth": "years"},
    {"prompt": "The word 'set' has the most dictionary _____.", "truth": "definitions"},
    {"prompt": "A blue whale's heart is about the size of a small _____.", "truth": "car"},
    {"prompt": "Tardigrades can survive the vacuum of _____.", "truth": "space"},
    {"prompt": "Crows can hold _____ and teach others.", "truth": "grudges"},
    {"prompt": "Elephants can recognize themselves in _____.", "truth": "mirrors"},
    {"prompt": "Pigs are considered as trainable as _____ in studies.", "truth": "dogs"},
    {"prompt": "Goats have accents that differ by _____.", "truth": "herd"},
    {"prompt": "The human nose can detect over a trillion _____.", "truth": "scents"},
    {"prompt": "Humans glow faintly but too weak to _____.", "truth": "see"},
    {"prompt": "The average cloud weighs over a million _____.", "truth": "pounds"},
    {"prompt": "A strand of spaghetti is called a _____.", "truth": "spaghetto"},
    {"prompt": "The dot over a lowercase i is called a _____.", "truth": "tittle"},
    {"prompt": "Bookkeeper has three consecutive double-letter _____.", "truth": "pairs"},
    {"prompt": "The first webcam watched a coffee _____ at Cambridge.", "truth": "pot"},
    {"prompt": "The first tweet said 'just setting up my _____.", "truth": "twttr"},
    {"prompt": "The first YouTube video was filmed at the San Diego _____.", "truth": "Zoo"},
    {"prompt": "The first domain ever registered was _____.com.", "truth": "Symbolics"},
    {"prompt": "Ada Lovelace is considered the first computer _____.", "truth": "programmer"},
    {"prompt": "The Magnavox Odyssey was an early home video game _____.", "truth": "console"},
    {"prompt": "Pong was not the first video game ever _____.", "truth": "created"},
    {"prompt": "The shortest commercial flight in the world lasts under two _____.", "truth": "minutes"},
    {"prompt": "Scotland's national animal is not a lion but a _____.", "truth": "unicorn"},
    {"prompt": "The inventor of the Pringles can is buried in a Pringles _____.", "truth": "can"},
    {"prompt": "There is a basketball court on the top floor of the U.S. Supreme _____.", "truth": "Court"},
    {"prompt": "Cows have best friends and get stressed when _____.", "truth": "separated"},
    {"prompt": "Dolphins have names for each _____.", "truth": "other"},
    {"prompt": "A shrimp's heart is in its _____.", "truth": "head"},
    {"prompt": "A flamingo eats with its head upside _____.", "truth": "down"},
    {"prompt": "Owls cannot move their _____.", "truth": "eyeballs"},
    {"prompt": "Starfish can regrow lost _____.", "truth": "arms"},
    {"prompt": "Jellyfish have no _____.", "truth": "brain"},
    {"prompt": "Mosquitoes are the deadliest animals to _____.", "truth": "humans"},
    {"prompt": "Humans are taller in the morning than at _____.", "truth": "night"},
    {"prompt": "Babies are born without _____.", "truth": "kneecaps"},
    {"prompt": "Your left lung is smaller to make room for your _____.", "truth": "heart"},
    {"prompt": "The hardest substance in the human body is tooth _____.", "truth": "enamel"},
    {"prompt": "Humans shed about 1.5 pounds of _____ per year.", "truth": "skin"},
    {"prompt": "The human liver can _____ much of itself after damage.", "truth": "regenerate"},
    {"prompt": "The human body has about 60,000 miles of blood _____.", "truth": "vessels"},
    {"prompt": "The human heart beats over 100,000 times per _____.", "truth": "day"},
    {"prompt": "Lactose tolerance in adults is a genetic _____ in some populations.", "truth": "adaptation"},
    {"prompt": "Peaches and nectarines are the same _____.", "truth": "species"},
    {"prompt": "Tomatoes are botanically _____.", "truth": "fruits"},
    {"prompt": "Peanuts are _____, not true nuts.", "truth": "legumes"},
    {"prompt": "Carrots were originally purple or _____.", "truth": "white"},
    {"prompt": "Spam is short for spiced ham, not _____ email.", "truth": "unsolicited"},
    {"prompt": "Nachos are named after Ignacio, nicknamed _____.", "truth": "Nacho"},
    {"prompt": "Tequila must come from specific regions of _____.", "truth": "Mexico"},
    {"prompt": "Scotch whisky must be made in _____.", "truth": "Scotland"},
    {"prompt": "Saffron is often more expensive than _____ by weight.", "truth": "gold"},
    {"prompt": "Vanilla is the second-most expensive spice after _____.", "truth": "saffron"},
    {"prompt": "Dark chocolate can be toxic to _____.", "truth": "dogs"},
    {"prompt": "Grapes and raisins can cause kidney failure in _____.", "truth": "dogs"},
    {"prompt": "Xylitol sweetener is extremely toxic to _____.", "truth": "dogs"},
    {"prompt": "Avocados contain persin, toxic to many _____.", "truth": "pets"},
    {"prompt": "Onions and garlic can damage red blood cells in _____.", "truth": "dogs"},
    {"prompt": "The human sneeze can exceed 100 _____.", "truth": "mph"},
    {"prompt": "Yawning may help cool the _____.", "truth": "brain"},
    {"prompt": "Laughing burns _____. ", "truth": "calories"},
    {"prompt": "The cornea gets oxygen from air, not _____.", "truth": "blood"},
    {"prompt": "Humans have fewer genes than some _____.", "truth": "grasses"},
    {"prompt": "A day on Mercury is longer than its _____.", "truth": "year"},
    {"prompt": "Saturn is less dense than _____.", "truth": "water"},
    {"prompt": "Neptune was discovered through math before direct _____.", "truth": "observation"},
    {"prompt": "Lightning is hotter than the surface of the _____.", "truth": "Sun"},
    {"prompt": "Antarctica is technically a desert by low _____", "truth": "precipitation"},
    {"prompt": "Mauna Kea is taller than Everest from the ocean _____.", "truth": "floor"},
    {"prompt": "The Dead Sea is one of the saltiest bodies of _____.", "truth": "water"},
    {"prompt": "The Nile is often cited as the longest _____.", "truth": "river"},
    {"prompt": "The Amazon carries more water than any other _____.", "truth": "river"},
    {"prompt": "The cheetah is the fastest land animal over short _____.", "truth": "distances"},
    {"prompt": "The blue whale is the largest animal ever _____.", "truth": "known"},
    {"prompt": "Sharks' skeletons are made of cartilage, not _____.", "truth": "bone"},
    {"prompt": "Bats are the only mammals capable of sustained _____.", "truth": "flight"},
    {"prompt": "Camels store fat in their humps, not _____.", "truth": "water"},
    {"prompt": "The Great Barrier Reef is the largest coral reef _____.", "truth": "system"},
    {"prompt": "Diamonds are made of _____ atoms.", "truth": "carbon"},
    {"prompt": "DNA stands for deoxyribonucleic _____.", "truth": "acid"},
    {"prompt": "Pluto was reclassified as a dwarf planet in _____.", "truth": "2006"},
    {"prompt": "The Wright brothers achieved powered flight in _____.", "truth": "1903"},
    {"prompt": "Penicillin was discovered by Alexander _____.", "truth": "Fleming"},
    {"prompt": "The printing press was popularized by Johannes _____.", "truth": "Gutenberg"},
    {"prompt": "The Roman Empire fell in the west in 476 _____.", "truth": "CE"},
    {"prompt": "The Internet originated from _____ research.", "truth": "ARPANET"},
    {"prompt": "The United Nations was founded in _____.", "truth": "1945"},
    {"prompt": "The first successful vaccine targeted _____.", "truth": "smallpox"},
    {"prompt": "The Mona Lisa hangs in the _____.", "truth": "Louvre"},
    {"prompt": "The Colosseum is located in _____.", "truth": "Rome"},
    {"prompt": "The Taj Mahal is in _____.", "truth": "India"},
    {"prompt": "The Sydney Opera House is in _____.", "truth": "Australia"},
    {"prompt": "The Statue of Liberty was a gift from _____.", "truth": "France"},
    {"prompt": "The Eiffel Tower was built for the 1889 World's _____.", "truth": "Fair"},
    {"prompt": "Oxford editors once planted a fake word as a copyright _____.", "truth": "trap"},
    {"prompt": "The word 'dude' once meant a fancy-dressed city _____.", "truth": "man"},
    {"prompt": "There was a war partly sparked by a soccer match between Honduras and El _____.", "truth": "Salvador"},
    {"prompt": "Mammoths were still alive when the Great Pyramid was _____.", "truth": "built"},
    {"prompt": "Cleopatra lived closer to the iPhone than to the pyramids' _____.", "truth": "construction"},
    {"prompt": "The Anglo-Zanzibar War is the shortest war on _____.", "truth": "record"},
    {"prompt": "The longest hiccuping spree lasted nearly 68 _____.", "truth": "years"},
    {"prompt": "A jiffy is an actual unit of time in _____.", "truth": "physics"},
    {"prompt": "The human appendix may help gut bacteria _____.", "truth": "recover"},
    {"prompt": "Fraternal twins can have different fathers in rare _____.", "truth": "cases"},
    {"prompt": "A person can survive with only one _____.", "truth": "kidney"},
    {"prompt": "AB positive blood is sometimes called the universal _____ type.", "truth": "recipient"},
    {"prompt": "Type O negative is often called the universal _____ type.", "truth": "donor"},
    {"prompt": "Caffeine metabolism speed varies _____.", "truth": "genetically"},
    {"prompt": "Helium voice happens because sound travels faster in thinner _____.", "truth": "air"},
    {"prompt": "Pure water is a poor conductor; dissolved ions make it _____.", "truth": "conductive"},
    {"prompt": "Auroras come from solar particles, not reflected _____.", "truth": "sunlight"},
    {"prompt": "Meteors glow mainly from ram pressure heating, not friction _____.", "truth": "alone"},
    {"prompt": "Gum passes through digestion like other _____.", "truth": "food"},
    {"prompt": "The five-second rule is a joke, not food _____ science.", "truth": "safety"},
    {"prompt": "Organic does not automatically mean more _____.", "truth": "nutritious"},
    {"prompt": "Most people tolerate MSG just _____.", "truth": "fine"},
    {"prompt": "Vein blood looks blue only through skin and _____.", "truth": "tissue"},
    {"prompt": "Humans have more than five sensory _____", "truth": "modalities"},
    {"prompt": "Seasons come from Earth's tilt, not its distance from the _____.", "truth": "Sun"},
    {"prompt": "Astronauts in orbit are still in Earth's gravity; they are in free _____.", "truth": "fall"},
    {"prompt": "Glass is an amorphous solid, not a slow-flowing _____.", "truth": "liquid"},
    {"prompt": "Diamonds form under pressure, not from compressed _____.", "truth": "coal"},
    {"prompt": "The Big Bang describes expanding space, not an explosion in existing _____.", "truth": "space"},
    {"prompt": "The Sun looks white from space; yellow is from Earth's _____.", "truth": "atmosphere"},
    {"prompt": "Black holes are not cosmic vacuum cleaners for everything _____.", "truth": "nearby"},
    {"prompt": "The universe has no single center like a bomb _____.", "truth": "site"},
    {"prompt": "Evolution is a well-tested scientific _____.", "truth": "theory"},
    {"prompt": "Humans and chimps share a common ancestor, not a direct chimp _____ line.", "truth": "descent"},
    {"prompt": "Dinosaurs went extinct long before humans _____.", "truth": "existed"},
    {"prompt": "Fortune cookies were popularized in America, not _____.", "truth": "China"},
    {"prompt": "The forbidden fruit in the Bible is never identified as an _____.", "truth": "apple"},
    {"prompt": "Nero was miles away when Rome burned; he did not _____.", "truth": "fiddle"},
    {"prompt": "Marie Antoinette probably never said 'let them eat _____.", "truth": "cake"},
    {"prompt": "George Washington's dentures were not made of _____.", "truth": "wood"},
    {"prompt": "Einstein did not fail math as a _____.", "truth": "student"},
    {"prompt": "Columbus did not prove the Earth was _____.", "truth": "round"},
    {"prompt": "Medieval Europeans did not widely believe the Earth was _____.", "truth": "flat"},
    {"prompt": "Thanksgiving sleepiness is mostly food volume, not just _____.", "truth": "turkey"},
    {"prompt": "You can report a missing person without waiting 24 _____.", "truth": "hours"},
    {"prompt": "Bird parents rarely abandon chicks because of human _____.", "truth": "touch"},
    {"prompt": "Detox diets do not remove toxins better than your _____.", "truth": "liver"},
    {"prompt": "Antibiotics do not work against viral infections like the common _____.", "truth": "cold"},
    {"prompt": "Vaccines do not cause _____.", "truth": "autism"},
    {"prompt": "Humans do not swallow eight spiders per year while _____.", "truth": "sleeping"},
    {"prompt": "Lightning can and does strike the same place _____.", "truth": "twice"},
    {"prompt": "Chameleons change color for mood and temperature, not just _____.", "truth": "camouflage"},
    {"prompt": "Ostriches do not bury their heads in _____.", "truth": "sand"},
    {"prompt": "Lemmings do not commit mass suicide off _____.", "truth": "cliffs"},
    {"prompt": "Bulls are colorblind to red; they react to _____.", "truth": "movement"},
    {"prompt": "Shaving does not make hair grow back thicker or _____.", "truth": "darker"},
    {"prompt": "Cracking knuckles does not cause _____.", "truth": "arthritis"},
    {"prompt": "Sugar does not cause hyperactivity in most _____.", "truth": "children"},
    {"prompt": "We use far more than 10% of our _____.", "truth": "brain"},
    {"prompt": "Goldfish remember for weeks, not three _____.", "truth": "seconds"},
    {"prompt": "Hair and nails do not keep growing after _____.", "truth": "death"},
    {"prompt": "You do not lose most body heat only through your _____.", "truth": "head"},
    {"prompt": "Microwave radiation does not make food _____.", "truth": "radioactive"},
    {"prompt": "Swallowed gum does not stay in your stomach for seven _____.", "truth": "years"},
    {"prompt": "The Great Wall is not visible from space with the naked _____.", "truth": "eye"},
    {"prompt": "SOS is a Morse pattern, not 'save our _____.", "truth": "ship"},
    {"prompt": "Toilet swirl direction is about plumbing, not the Coriolis _____.", "truth": "effect"},
    {"prompt": "Feed a cold, starve a fever is folk advice, not medical _____.", "truth": "doctrine"},
    {"prompt": "Colds are caused by viruses, not cold _____.", "truth": "weather"},
    {"prompt": "Reading in dim light strains eyes but does not permanently ruin _____.", "truth": "vision"},
    {"prompt": "Carrots help eye health but do not grant night _____.", "truth": "vision"},
    {"prompt": "Twinkies do expire despite the popular _____.", "truth": "myth"},
    {"prompt": "The Sahara is not the world's largest _____ desert.", "truth": "overall"},
    {"prompt": "Mount Everest is highest above sea level, not from base to _____.", "truth": "peak"},
    {"prompt": "Water is a poor conductor until it has dissolved _____.", "truth": "ions"},
    {"prompt": "Sound cannot travel through a true vacuum without a _____.", "truth": "medium"},
]

# --- DRAW GUESS (350 drawable absurd scenes) ---

DRAW_GUESS: list[str] = [
    "A cat riding a skateboard through a drive-thru",
    "An angry toaster at therapy",
    "A wizard waiting at the DMV",
    "A penguin in a hot tub with sunglasses",
    "A dragon eating a salad at a fancy restaurant",
    "A robot having a dramatic bad hair day",
    "A shark wearing a tutu on stage",
    "A cactus giving a motivational speech",
    "A raccoon stealing a whole wedding cake",
    "A llama DJ at a silent disco",
    "A bear in a tuxedo on a unicycle",
    "A goose security guard at a nightclub",
    "A capybara floating in a pool with a drink",
    "A sloth winning a sprint race in slow motion",
    "A frog doing taxes at a tiny desk",
    "A lobster driving a convertible",
    "A penguin proposing to a vending machine",
    "A cat lawyer arguing with a dog judge",
    "A haunted vending machine at a gym",
    "A sentient Roomba chasing a ghost",
    "A taco riding a roller coaster",
    "A pizza slice running from a hungry college student",
    "A burrito doing yoga on a mountain",
    "A nacho chip surfing a wave of queso",
    "A hot dog in a tuxedo at prom",
    "A waffle iron having an existential crisis",
    "A coffee cup filing for divorce from a donut",
    "A beer pong table at a funeral",
    "A red solo cup accepting an award",
    "A ping pong paddle in couples therapy",
    "A frat house haunted by good decisions",
    "A spring break airplane with one bathroom",
    "A Vegas chapel with a long line of regrets",
    "A roster written on a bar napkin",
    "A situationship chart on a whiteboard",
    "A group chat exploding into fireworks",
    "A drunk text being launched like a missile",
    "A hangover monster under a bunk bed",
    "A credit card declining at the worst moment",
    "A dating app profile reviewed by a tribunal",
    "A red flag parade down Main Street",
    "A walk of shame red carpet",
    "A 2am DoorDash knight in armor",
    "A finsta account behind a vault door",
    "A Roman Empire brain museum exhibit",
    "A toxic trait Pokémon battle",
    "A brunch cult initiation ceremony",
    "A situationship weather forecast: chaotic",
    "A roster rotation wheel of fortune",
    "A ghoster vanishing from a dinner table",
    "A soft launch missile silo",
    "A hard launch parade float",
    "A main character cape that's too small",
    "A delulu cloud over a college campus",
    "A rizz meter running on empty",
    "A ick face at a fancy dinner",
    "A no cap hat that literally has no cap",
    "A slay button stuck in the on position",
    "A brain rot garden growing memes",
    "A group trip planning meeting turning into war",
    "A Airbnb with one shower and eight guys",
    "A pregame turning into a board meeting",
    "A afterparty inside a Waffle House",
    "A Uber pool with your ex and your mom",
    "A Zoom date with a fake background of success",
    "A LinkedIn photo vs reality split screen",
    "A gym bro skipping leg day forever",
    "A protein shake crying in the corner",
    "A dumbbell judging someone's form",
    "A yoga class that is actually pregame stretches",
    "A meditation app screaming notifications",
    "A silent retreat with a karaoke breakout",
    "A trust fall where nobody catches anyone",
    "A company retreat on a sinking paddle boat",
    "A performance review in a haunted office",
    "A job interview in a brewery taproom",
    "A resume printed on a napkin",
    "A cover letter written by ChatGPT with confidence",
    "A student loan monster under the bed",
    "A diploma frame holding a receipt",
    "A college dining hall serving regret",
    "A finals week zombie apocalypse",
    "A professor's email marked URGENT at 11pm",
    "A group project where one person does everything",
    "A PowerPoint that is just memes",
    "A thesis defense with a piñata",
    "A graduation cap thrown into a lake",
    "A wedding where the cake is a Costco sheet",
    "A bachelor party piñata filled with regrets",
    "A bridezilla riding a chariot of bridesmaids",
    "A groom trying to escape through a window",
    "A divorce party with a piñata of wedding photos",
    "A baby shower with a gender reveal grenade",
    "A gender reveal causing a minor explosion",
    "A family reunion dodgeball with secrets",
    "A Thanksgiving turkey wearing headphones",
    "A Christmas dinner political debate arena",
    "A New Year's kiss with the wrong person",
    "A Valentine's Day card from your situationship",
    "A Halloween costume that's just emotional damage",
    "A Easter egg hunt for red flags",
    "A Fourth of July fireworks of bad texts",
    "A haunted frat basement at 3am",
    "A haunted laundry room during finals",
    "A haunted dating app loading screen",
    "A haunted group chat notification",
    "A haunted Uber rating of 4.9",
    "A haunted spring break Polaroid",
    "A haunted Vegas wedding photo",
    "A haunted college advisor's office",
    "A haunted dining hall meatloaf",
    "A haunted bathroom line at a party",
    "A haunted solo cup pyramid",
    "A haunted pong table final boss",
    "A haunted karaoke machine singing breakup songs",
    "A haunted beer funnel of bad decisions",
    "A haunted red cup tower of regrets",
    "A haunted pong ball with mind control",
    "A haunted flip cup timer counting your life choices",
    "A haunted dartboard of ex names",
    "A haunted pool table with relationship drama",
    "A haunted smoke machine at a frat formal",
    "A haunted disco ball of situationships",
    "A haunted DJ playing only Drake",
    "A haunted dance floor split in half by an ex",
    "A haunted bathroom mirror rating your outfit",
    "A haunted coat check full of lost dignity",
    "A haunted Uber queue at closing time",
    "A haunted pizza at 3am delivery driver",
    "A haunted ramen cup judging your life",
    "A haunted cereal bowl at midnight",
    "A haunted gas station hot dog under a heat lamp",
    "A haunted vending machine that only takes exact change and dignity",
    "A haunted microwave with a 3am burrito",
    "A haunted air fryer of drunk food",
    "A haunted grill at a tailgate",
    "A haunted charcuterie board at a wine night",
    "A haunted cheese pull of emotional attachment",
    "A haunted avocado toast of gentrification",
    "A haunted brunch line wrapped around the block",
    "A haunted mimosa tower of poor choices",
    "A haunted espresso martini with trust issues",
    "A haunted tequila shot with flashbacks",
    "A haunted whiskey neat with regrets",
    "A haunted beer bong of peer pressure",
    "A haunted wine mom energy at age 22",
    "A haunted keg stand championship belt",
    "A haunted jungle juice cauldron",
    "A haunted punch bowl of unknown alcohol",
    "A haunted red solo cup army",
    "A haunted pong ball entering another dimension",
    "A haunted flip cup gravity anomaly",
    "A haunted beer pong island nation",
    "A haunted tailgate in a parking garage",
    "A haunted stadium bathroom line",
    "A haunted concession stand price tag",
    "A haunted foam finger of denial",
    "A haunted face paint of team spirit and dehydration",
    "A haunted jersey of an ex's favorite team",
    "A haunted march madness bracket on fire",
    "A haunted fantasy football roster of exes",
    "A haunted sports bar wing sauce too hot to handle",
    "A haunted pickleball court of retirees judging you",
    "A haunted golf cart chase on a course",
    "A haunted ski lift stuck with your ex",
    "A haunted beach volleyball with sunburn regrets",
    "A haunted surfboard wiping out your dignity",
    "A haunted paddleboard of instability",
    "A haunted kayak with a leaking situationship",
    "A haunted camping tent with eight snorers",
    "A haunted campfire story about your roster",
    "A haunted s'more with emotional layers",
    "A haunted sleeping bag full of regret",
    "A haunted hiking trail called Walk of Shame Ridge",
    "A haunted mountain peak of hubris",
    "A haunted zipline over a breakup canyon",
    "A haunted rope swing into a lake of bad texts",
    "A haunted cliff jump of questionable judgment",
    "A haunted boat party with one life jacket",
    "A haunted yacht that is actually a pontoon",
    "A haunted cruise spring break outbreak",
    "A haunted airport security bin of shame",
    "A haunted TSA agent reading your mind",
    "A haunted passport stamp of Vegas",
    "A haunted suitcase overweight with souvenirs and secrets",
    "A haunted hotel minibar pricing your soul",
    "A haunted resort pool with no towels left",
    "A haunted all-inclusive bracelet of captivity",
    "A haunted timeshare presentation trap",
    "A haunted Airbnb review war",
    "A haunted hostel bunk bed creaking with drama",
    "A haunted road trip playlist of ex songs",
    "A haunted GPS rerouting through your feelings",
    "A haunted gas station bathroom key on a giant chain",
    "A haunted rest stop vending machine dinner",
    "A haunted car karaoke of breakup anthems",
    "A haunted passenger seat of unresolved tension",
    "A haunted backseat driver of your mom",
    "A haunted trunk full of laundry you forgot to do",
    "A haunted parking ticket on a dream date",
    "A haunted tow truck taking your dignity",
    "A haunted flat tire on the way to her place",
    "A haunted check engine light at prom",
    "A haunted Uber surge pricing your desperation",
    "A haunted Lyft pink mustache of false hope",
    "A haunted scooter ride without a helmet",
    "A haunted bike share with a broken seat",
    "A haunted subway turnstile of commitment issues",
    "A haunted bus stop confession booth",
    "A haunted train delay of emotional baggage",
    "A haunted plane turbulence during a proposal",
    "A haunted middle seat between two exes",
    "A haunted overhead bin too small for your ego",
    "A haunted life vest fashion show",
    "A haunted emergency exit slide party",
    "A haunted passport control questioning your choices",
    "A haunted customs dog sniffing your secrets",
    "A haunted duty free cologne called Regret",
    "A haunted airport bar at 6am",
    "A haunted red eye flight of walk of shame",
    "A haunted layover in your feelings",
    "A haunted baggage claim of mixed signals",
    "A haunted lost luggage of your personality",
    "A haunted hotel 'do not disturb' ignored by life",
    "A haunted room service burger at 2am",
    "A haunted minibar peanut pricing your dignity",
    "A haunted hotel gym with one treadmill",
    "A haunted rooftop pool with no entry after drama",
    "A haunted casino slot machine of your GPA",
    "A haunted blackjack table of roster odds",
    "A haunted roulette wheel of red flags",
    "A haunted poker face during a text from your ex",
    "A haunted craps table of emotional dice",
    "A haunted showgirl costume in your size of bad decisions",
    "A haunted Elvis impersonator marrying strangers",
    "A haunted chapel drive-thru wedding",
    "A haunted wedding ring vending machine",
    "A haunted bouquet toss hitting the wrong person",
    "A haunted garter toss of discomfort",
    "A haunted first dance on a sticky floor",
    "A haunted wedding DJ playing your song with your ex",
    "A haunted open bar closing just as you arrive",
    "A haunted champagne tower of foam, not champagne",
    "A haunted cake smash of relationship status",
    "A haunted photo booth strip of regrettable poses",
    "A haunted sparkler send-off fire hazard",
    "A haunted afterparty in the hotel hallway",
    "A haunted room number mix-up with your ex",
    "A haunted elevator ride of awkward silence",
    "A haunted hotel hot tub with too many people",
    "A haunted continental breakfast of sadness",
    "A haunted waffle maker at a budget hotel",
    "A haunted coffee station with no cream",
    "A haunted business center printing your sins",
    "A haunted hotel printer out of toner and hope",
    "A haunted conference room team building exercise",
    "A haunted office party photocopier incident",
    "A haunted water cooler gossip tsunami",
    "A haunted break room microwave fish crime",
    "A haunted stapler in a passive-aggressive war",
    "A haunted Post-it note that says 'we need to talk'",
    "A haunted email 'reply all' mushroom cloud",
    "A haunted calendar invite titled 'Quick Chat'",
    "A haunted Slack status 'brb crying'",
    "A haunted Zoom camera accidentally on",
    "A haunted mute button betrayal",
    "A haunted screen share of your browser history",
    "A haunted Google Doc of roster rankings",
    "A haunted spreadsheet of ex compatibility scores",
    "A haunted PowerPoint transition of emotional damage",
    "A haunted laser pointer of judgment",
    "A haunted whiteboard eraser removing your excuses",
    "A haunted marker smell of college trauma",
    "A haunted textbook you never opened",
    "A haunted highlighter marking only the wrong answers",
    "A haunted scantron sheet of random guesses",
    "A haunted blue book exam of pure panic",
    "A haunted calculator with no batteries",
    "A haunted laptop fan sounding like a jet",
    "A haunted charger cable with one bend too many",
    "A haunted phone at 1% during an important call",
    "A haunted notification banner from your ex",
    "A haunted read receipt turned on",
    "A haunted typing bubble that never sends",
    "A haunted delivered message with no reply",
    "A haunted left on read graveyard",
    "A haunted screenshot sound in a quiet room",
    "A haunted accidental like on a 2014 photo",
    "A haunted finsta follow request from your mom",
    "A haunted close friends list betrayal",
    "A haunted story view order investigation",
    "A haunted DM slide into the wrong person",
    "A haunted group chat name change coup",
    "A haunted pinned message of ancient drama",
    "A haunted voice note waveform of drunk emotion",
    "A haunted meme reaction that started a war",
    "A haunted GIF that aged poorly",
    "A haunted emoji poll with no winning option",
    "A haunted calendar reminder: 'her birthday'",
    "A haunted alarm snooze championship",
    "A haunted sleep tracker shaming your choices",
    "A haunted step counter disappointed in you",
    "A haunted smart watch asking if you're okay",
    "A haunted airpod case with one missing pod",
    "A haunted bluetooth pairing with your ex's speaker",
    "A haunted aux cord battle at a party",
    "A haunted speaker dying mid-banger",
    "A haunted playlist shuffle playing your trauma",
    "A haunted Spotify wrapped of red flags",
    "A haunted vinyl record of your sad boy hours",
    "A haunted guitar serenade outside the wrong window",
    "A haunted karaoke duet with a stranger",
    "A haunted microphone feedback scream",
    "A haunted trumpet solo at the wrong funeral",
    "A haunted drum solo during a quiet moment",
    "A haunted saxophone romance in a parking lot",
    "A haunted violin sad moment in a comedy",
    "A haunted piano bar of heartbreak",
    "A haunted jukebox that only plays breakup songs",
    "A haunted nightclub bathroom line philosophy seminar",
    "A haunted bouncer judging your outfit and soul",
    "A haunted velvet rope of social hierarchy",
    "A haunted VIP section of people you don't know",
    "A haunted bottle service sparkler burning money",
    "A haunted glow stick graveyard on the floor",
    "A haunted strobe light revealing bad decisions",
    "A haunted fog machine hiding your walk of shame",
    "A haunted laser show of your roster",
    "A haunted disco floor stickiness level: maximum",
    "A haunted coat check ticket you lost immediately",
    "A haunted after-hours diner of confession",
    "A haunted waffle house plate of peace talks",
    "A haunted diner coffee refill of false hope",
    "A haunted pancake stack of layered feelings",
    "A haunted syrup bottle stuck shut like your emotions",
    "A haunted bacon strip of sizzling tension",
    "A haunted hash browns scattered like your plans",
    "A haunted omelette with too many ingredients",
    "A haunted toast that pops up unexpectedly",
    "A haunted blender smoothie of kale and denial",
    "A haunted protein shaker leak in your gym bag",
    "A haunted meal prep container of sadness",
    "A haunted Tupperware lid that never matches",
    "A haunted fridge light revealing leftover pizza",
    "A haunted freezer burned ice cream of nostalgia",
    "A haunted microwave timer counting down your patience",
    "A haunted smoke detector during a cooking date",
    "A haunted fire extinguisher at a gender reveal",
    "A haunted sprinkler system at a house party",
    "A haunted neighbor banging on the wall at 2am",
    "A haunted HOA letter about your lawn and lifestyle",
    "A haunted landlord inspection during chaos",
    "A haunted security deposit evaporating",
    "A haunted roommate chore chart ignored by all",
    "A haunted passive-aggressive note on the fridge",
    "A haunted shared bathroom schedule war",
    "A haunted hot water running out mid-shower",
    "A haunted clogged shower drain of hair and secrets",
    "A haunted toilet paper roll installed the wrong way",
    "A haunted plunger hero moment",
    "A haunted laundry mountain in the corner",
    "A haunted missing sock dimension portal",
    "A haunted dryer sheet stuck in a hoodie",
    "A haunted iron burn on a shirt before a date",
    "A haunted lint roller saving your black outfit",
    "A haunted vacuum eating your charger",
    "A haunted Roomba spreading a mess wider",
    "A haunted mop bucket of tears",
    "A haunted broom sweeping problems under rug",
    "A haunted trash bag that won't tie shut",
    "A haunted recycling bin of empty bottles and excuses",
    "A haunted compost bin of rotting intentions",
    "A haunted plant you killed with love",
    "A haunted succulent that survived your roster",
    "A haunted goldfish outliving your situationship",
    "A haunted hamster wheel of overthinking",
    "A haunted dog eating homework and dignity",
    "A haunted cat knocking your drink off the table",
    "A haunted parrot repeating your drunk texts",
    "A haunted snake escaping during a date",
    "A haunted ferret stealing your keys",
    "A haunted iguana judging your decor",
    "A haunted tarantula in a roommate prank",
    "A haunted fish tank algae of neglect",
    "A haunted pet portrait better than your selfies",
    "A haunted vet bill after the party trick failed",
    "A haunted dog park politics summit",
    "A haunted cat cafe emotional support overload",
    "A haunted horse on a Tinder date picnic",
    "A haunted cow mooing during a serious talk",
    "A haunted chicken crossing your career path",
    "A haunted pig in a blanket costume contest",
    "A haunted sheep counting you to sleep",
    "A haunted goat screaming like your group chat",
    "A haunted llama spitting truth",
    "A haunted alpaca haircut better than yours",
    "A haunted camel storing drama in its hump",
    "A haunted elephant never forgetting your ex",
    "A haunted giraffe with a long neck for gossip",
    "A haunted zebra with commitment stripe issues",
    "A haunted lion mane of confidence and lint",
    "A haunted tiger in a tiny cardboard box",
    "A haunted bear stealing a picnic of boundaries",
    "A haunted panda eating bamboo and your time",
    "A haunted koala clinging to the wrong person",
    "A haunted kangaroo pouch full of unpaid tabs",
    "A haunted platypus of mixed signals",
    "A haunted otter holding hands with the wrong otter",
    "A haunted seal clapping at your bad idea",
    "A haunted walrus mustache of wisdom",
    "A haunted penguin sliding into your DMs",
    "A haunted puffin with a colorful beak of lies",
    "A haunted parrot on a pirate shoulder of bad advice",
    "A haunted owl delivering a 3am truth bomb",
    "A haunted bat hanging upside down like your sleep schedule",
    "A haunted crow collecting shiny red flags",
    "A haunted pigeon strutting like it owns the city",
    "A haunted seagull stealing your boardwalk fries",
    "A haunted pelican swallowing your phone",
    "A haunted flamingo standing on one leg of stability",
    "A haunted peacock showing off for no one",
    "A haunted turkey pardoned by the governor of regret",
    "A haunted chicken nugget shaped like a country",
    "A haunted egg with a double yolk of fate",
    "A haunted avocado pit growing in your sink",
    "A haunted lemon life gave you at the worst time",
    "A haunted lime wedge in a questionable drink",
    "A haunted coconut falling on your main character moment",
    "A haunted pineapple on pizza trial courtroom",
    "A haunted watermelon seed spitting contest of egos",
    "A haunted grape stomping your patience",
    "A haunted banana peel of hubris on the sidewalk",
    "A haunted apple a day keeping your therapist employed",
    "A haunted orange juice after brushing teeth betrayal",
    "A haunted milk carton missing person: your motivation",
    "A haunted cheese wheel rolling away from responsibility",
    "A haunted bread loaf rising like your anxiety",
    "A haunted baguette sword fight in a bakery",
    "A haunted croissant flake explosion on a black shirt",
    "A haunted donut with sprinkles of denial",
    "A haunted bagel with schmear of emotional baggage",
    "A haunted muffin top that's not the joke you think",
    "A haunted cupcake with too much frosting of feelings",
    "A haunted birthday cake with one sad candle",
    "A haunted wedding cake tier of unstable relationships",
    "A haunted pie cooling on a windowsill of temptation",
    "A haunted pizza delivery guy witnessing a breakup",
    "A haunted calzone sealed with secrets",
    "A haunted hot pocket lava mouth incident",
    "A haunted ramen bowl of college survival",
    "A haunted pho steam fogging your glasses and future",
    "A haunted sushi roll of questionable choices",
    "A haunted taco shell cracking under pressure",
    "A haunted quesadilla triangle of life decisions",
    "A haunted nacho chip breaking at the dip moment",
    "A haunted guacamole turning brown like your mood",
    "A haunted salsa jar lid stuck like your situationship",
    "A haunted churro dust storm on your clothes",
    "A haunted ice cream cone dripping on your hand",
    "A haunted popsicle staining your childhood and shirt",
    "A haunted milkshake bringing all the drama to the yard",
    "A haunted smoothie with spinach and delusion",
    "A haunted energy drink wings that don't work",
    "A haunted coffee spill on a white shirt before interview",
    "A haunted espresso shot of panic",
    "A haunted latte art heart broken in foam",
    "A haunted tea bag steeping in gossip",
    "A haunted boba straw clogging like your plans",
    "A haunted kombucha scoby named Keith",
    "A haunted protein bar tasting like cardboard and hope",
    "A haunted trail mix picking out only the chocolate",
    "A haunted chip bag mostly air and disappointment",
    "A haunted popcorn kernel stuck in your teeth forever",
    "A haunted pretzel twist of complicated feelings",
    "A haunted cotton candy dissolving like your resolve",
    "A haunted funnel cake at the county fair of mistakes",
    "A haunted corn dog of questionable life choices",
    "A haunted turkey leg at a Renaissance fair of delusion",
    "A haunted giant turkey leg of power and grease",
    "A haunted lobster bib at a fancy date",
    "A haunted crab crack tool battle",
    "A haunted oyster shucking your expectations",
    "A haunted shrimp cocktail of awkward networking",
    "A haunted clam chowder bread bowl of comfort",
    "A haunted fish and chips in newspaper of old news",
    "A haunted fish taco Tuesday of destiny",
    "A haunted clam bake of unresolved tension",
    "A haunted clam casino of gambling on love",
]